//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for antennaLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="antennaLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="antennaLocation" type="{}vector3Double" minOccurs="0"/>
 *         &lt;element name="relativeAntennaLocation" type="{}vector3Float" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "antennaLocation", propOrder = {
    "antennaLocation",
    "relativeAntennaLocation"
})
public class AntennaLocation {

    protected Vector3Double antennaLocation;
    protected Vector3Float relativeAntennaLocation;

    /**
     * Gets the value of the antennaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Double }
     *     
     */
    public Vector3Double getAntennaLocation() {
        return antennaLocation;
    }

    /**
     * Sets the value of the antennaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Double }
     *     
     */
    public void setAntennaLocation(Vector3Double value) {
        this.antennaLocation = value;
    }

    /**
     * Gets the value of the relativeAntennaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Float }
     *     
     */
    public Vector3Float getRelativeAntennaLocation() {
        return relativeAntennaLocation;
    }

    /**
     * Sets the value of the relativeAntennaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Float }
     *     
     */
    public void setRelativeAntennaLocation(Vector3Float value) {
        this.relativeAntennaLocation = value;
    }

}
