//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for detonationPdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="detonationPdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}warfareFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="articulationParameters" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="burstDescriptor" type="{}burstDescriptor" minOccurs="0"/>
 *         &lt;element name="detonationResult" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="eventID" type="{}eventID" minOccurs="0"/>
 *         &lt;element name="locationInWorldCoordinates" type="{}vector3Double" minOccurs="0"/>
 *         &lt;element name="munitionID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="numberOfArticulationParameters" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="pad" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="velocity" type="{}vector3Float" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "detonationPdu", propOrder = {
    "articulationParameters",
    "burstDescriptor",
    "detonationResult",
    "eventID",
    "locationInWorldCoordinates",
    "munitionID",
    "numberOfArticulationParameters",
    "pad",
    "velocity"
})
public class DetonationPdu
    extends WarfareFamilyPdu
{

    @XmlElement(nillable = true)
    protected List<Object> articulationParameters;
    protected BurstDescriptor burstDescriptor;
    protected short detonationResult;
    protected EventID eventID;
    protected Vector3Double locationInWorldCoordinates;
    protected EntityID munitionID;
    protected short numberOfArticulationParameters;
    protected short pad;
    protected Vector3Float velocity;

    /**
     * Gets the value of the articulationParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articulationParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticulationParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getArticulationParameters() {
        if (articulationParameters == null) {
            articulationParameters = new ArrayList<Object>();
        }
        return this.articulationParameters;
    }

    /**
     * Gets the value of the burstDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link BurstDescriptor }
     *     
     */
    public BurstDescriptor getBurstDescriptor() {
        return burstDescriptor;
    }

    /**
     * Sets the value of the burstDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BurstDescriptor }
     *     
     */
    public void setBurstDescriptor(BurstDescriptor value) {
        this.burstDescriptor = value;
    }

    /**
     * Gets the value of the detonationResult property.
     * 
     */
    public short getDetonationResult() {
        return detonationResult;
    }

    /**
     * Sets the value of the detonationResult property.
     * 
     */
    public void setDetonationResult(short value) {
        this.detonationResult = value;
    }

    /**
     * Gets the value of the eventID property.
     * 
     * @return
     *     possible object is
     *     {@link EventID }
     *     
     */
    public EventID getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventID }
     *     
     */
    public void setEventID(EventID value) {
        this.eventID = value;
    }

    /**
     * Gets the value of the locationInWorldCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Double }
     *     
     */
    public Vector3Double getLocationInWorldCoordinates() {
        return locationInWorldCoordinates;
    }

    /**
     * Sets the value of the locationInWorldCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Double }
     *     
     */
    public void setLocationInWorldCoordinates(Vector3Double value) {
        this.locationInWorldCoordinates = value;
    }

    /**
     * Gets the value of the munitionID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getMunitionID() {
        return munitionID;
    }

    /**
     * Sets the value of the munitionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setMunitionID(EntityID value) {
        this.munitionID = value;
    }

    /**
     * Gets the value of the numberOfArticulationParameters property.
     * 
     */
    public short getNumberOfArticulationParameters() {
        return numberOfArticulationParameters;
    }

    /**
     * Sets the value of the numberOfArticulationParameters property.
     * 
     */
    public void setNumberOfArticulationParameters(short value) {
        this.numberOfArticulationParameters = value;
    }

    /**
     * Gets the value of the pad property.
     * 
     */
    public short getPad() {
        return pad;
    }

    /**
     * Sets the value of the pad property.
     * 
     */
    public void setPad(short value) {
        this.pad = value;
    }

    /**
     * Gets the value of the velocity property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Float }
     *     
     */
    public Vector3Float getVelocity() {
        return velocity;
    }

    /**
     * Sets the value of the velocity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Float }
     *     
     */
    public void setVelocity(Vector3Float value) {
        this.velocity = value;
    }

}
