//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for electronicEmissionsPdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="electronicEmissionsPdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}distributedEmissionsFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="emittingEntityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="eventID" type="{}eventID" minOccurs="0"/>
 *         &lt;element name="numberOfSystems" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="stateUpdateIndicator" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="systems" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "electronicEmissionsPdu", propOrder = {
    "emittingEntityID",
    "eventID",
    "numberOfSystems",
    "stateUpdateIndicator",
    "systems"
})
public class ElectronicEmissionsPdu
    extends DistributedEmissionsFamilyPdu
{

    protected EntityID emittingEntityID;
    protected EventID eventID;
    protected short numberOfSystems;
    protected short stateUpdateIndicator;
    @XmlElement(nillable = true)
    protected List<Object> systems;

    /**
     * Gets the value of the emittingEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getEmittingEntityID() {
        return emittingEntityID;
    }

    /**
     * Sets the value of the emittingEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setEmittingEntityID(EntityID value) {
        this.emittingEntityID = value;
    }

    /**
     * Gets the value of the eventID property.
     * 
     * @return
     *     possible object is
     *     {@link EventID }
     *     
     */
    public EventID getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventID }
     *     
     */
    public void setEventID(EventID value) {
        this.eventID = value;
    }

    /**
     * Gets the value of the numberOfSystems property.
     * 
     */
    public short getNumberOfSystems() {
        return numberOfSystems;
    }

    /**
     * Sets the value of the numberOfSystems property.
     * 
     */
    public void setNumberOfSystems(short value) {
        this.numberOfSystems = value;
    }

    /**
     * Gets the value of the stateUpdateIndicator property.
     * 
     */
    public short getStateUpdateIndicator() {
        return stateUpdateIndicator;
    }

    /**
     * Sets the value of the stateUpdateIndicator property.
     * 
     */
    public void setStateUpdateIndicator(short value) {
        this.stateUpdateIndicator = value;
    }

    /**
     * Gets the value of the systems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getSystems() {
        if (systems == null) {
            systems = new ArrayList<Object>();
        }
        return this.systems;
    }

}
