//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entityStatePdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entityStatePdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}entityInformationFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="alternativeEntityType" type="{}entityType" minOccurs="0"/>
 *         &lt;element name="articulationParameters" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="capabilities" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="deadReckoningParameters" type="{}deadReckoningParameter" minOccurs="0"/>
 *         &lt;element name="entityAppearance" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="entityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="entityLinearVelocity" type="{}vector3Float" minOccurs="0"/>
 *         &lt;element name="entityLocation" type="{}vector3Double" minOccurs="0"/>
 *         &lt;element name="entityOrientation" type="{}orientation" minOccurs="0"/>
 *         &lt;element name="entityType" type="{}entityType" minOccurs="0"/>
 *         &lt;element name="forceId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="marking" type="{}marking" minOccurs="0"/>
 *         &lt;element name="numberOfArticulationParameters" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entityStatePdu", propOrder = {
    "alternativeEntityType",
    "articulationParameters",
    "capabilities",
    "deadReckoningParameters",
    "entityAppearance",
    "entityID",
    "entityLinearVelocity",
    "entityLocation",
    "entityOrientation",
    "entityType",
    "forceId",
    "marking",
    "numberOfArticulationParameters"
})
public class EntityStatePdu
    extends EntityInformationFamilyPdu
{

    protected EntityType alternativeEntityType;
    @XmlElement(nillable = true)
    protected List<Object> articulationParameters;
    protected int capabilities;
    protected DeadReckoningParameter deadReckoningParameters;
    protected int entityAppearance;
    protected EntityID entityID;
    protected Vector3Float entityLinearVelocity;
    protected Vector3Double entityLocation;
    protected Orientation entityOrientation;
    protected EntityType entityType;
    protected short forceId;
    protected Marking marking;
    protected byte numberOfArticulationParameters;

    /**
     * Gets the value of the alternativeEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link EntityType }
     *     
     */
    public EntityType getAlternativeEntityType() {
        return alternativeEntityType;
    }

    /**
     * Sets the value of the alternativeEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityType }
     *     
     */
    public void setAlternativeEntityType(EntityType value) {
        this.alternativeEntityType = value;
    }

    /**
     * Gets the value of the articulationParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articulationParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticulationParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getArticulationParameters() {
        if (articulationParameters == null) {
            articulationParameters = new ArrayList<Object>();
        }
        return this.articulationParameters;
    }

    /**
     * Gets the value of the capabilities property.
     * 
     */
    public int getCapabilities() {
        return capabilities;
    }

    /**
     * Sets the value of the capabilities property.
     * 
     */
    public void setCapabilities(int value) {
        this.capabilities = value;
    }

    /**
     * Gets the value of the deadReckoningParameters property.
     * 
     * @return
     *     possible object is
     *     {@link DeadReckoningParameter }
     *     
     */
    public DeadReckoningParameter getDeadReckoningParameters() {
        return deadReckoningParameters;
    }

    /**
     * Sets the value of the deadReckoningParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeadReckoningParameter }
     *     
     */
    public void setDeadReckoningParameters(DeadReckoningParameter value) {
        this.deadReckoningParameters = value;
    }

    /**
     * Gets the value of the entityAppearance property.
     * 
     */
    public int getEntityAppearance() {
        return entityAppearance;
    }

    /**
     * Sets the value of the entityAppearance property.
     * 
     */
    public void setEntityAppearance(int value) {
        this.entityAppearance = value;
    }

    /**
     * Gets the value of the entityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getEntityID() {
        return entityID;
    }

    /**
     * Sets the value of the entityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setEntityID(EntityID value) {
        this.entityID = value;
    }

    /**
     * Gets the value of the entityLinearVelocity property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Float }
     *     
     */
    public Vector3Float getEntityLinearVelocity() {
        return entityLinearVelocity;
    }

    /**
     * Sets the value of the entityLinearVelocity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Float }
     *     
     */
    public void setEntityLinearVelocity(Vector3Float value) {
        this.entityLinearVelocity = value;
    }

    /**
     * Gets the value of the entityLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Double }
     *     
     */
    public Vector3Double getEntityLocation() {
        return entityLocation;
    }

    /**
     * Sets the value of the entityLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Double }
     *     
     */
    public void setEntityLocation(Vector3Double value) {
        this.entityLocation = value;
    }

    /**
     * Gets the value of the entityOrientation property.
     * 
     * @return
     *     possible object is
     *     {@link Orientation }
     *     
     */
    public Orientation getEntityOrientation() {
        return entityOrientation;
    }

    /**
     * Sets the value of the entityOrientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Orientation }
     *     
     */
    public void setEntityOrientation(Orientation value) {
        this.entityOrientation = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link EntityType }
     *     
     */
    public EntityType getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityType }
     *     
     */
    public void setEntityType(EntityType value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the forceId property.
     * 
     */
    public short getForceId() {
        return forceId;
    }

    /**
     * Sets the value of the forceId property.
     * 
     */
    public void setForceId(short value) {
        this.forceId = value;
    }

    /**
     * Gets the value of the marking property.
     * 
     * @return
     *     possible object is
     *     {@link Marking }
     *     
     */
    public Marking getMarking() {
        return marking;
    }

    /**
     * Sets the value of the marking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Marking }
     *     
     */
    public void setMarking(Marking value) {
        this.marking = value;
    }

    /**
     * Gets the value of the numberOfArticulationParameters property.
     * 
     */
    public byte getNumberOfArticulationParameters() {
        return numberOfArticulationParameters;
    }

    /**
     * Sets the value of the numberOfArticulationParameters property.
     * 
     */
    public void setNumberOfArticulationParameters(byte value) {
        this.numberOfArticulationParameters = value;
    }

}
