//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for griddedDataPdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="griddedDataPdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}syntheticEnvironmentFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="constantGrid" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="coordinateSystem" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="environmentType" type="{}entityType" minOccurs="0"/>
 *         &lt;element name="environmentalSimulationApplicationID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="fieldNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="gridDataList" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="numberOfGridAxes" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="orientation" type="{}orientation" minOccurs="0"/>
 *         &lt;element name="padding1" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="padding2" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="pduNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pduTotal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="sampleTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="totalValues" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="vectorDimension" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "griddedDataPdu", propOrder = {
    "constantGrid",
    "coordinateSystem",
    "environmentType",
    "environmentalSimulationApplicationID",
    "fieldNumber",
    "gridDataList",
    "numberOfGridAxes",
    "orientation",
    "padding1",
    "padding2",
    "pduNumber",
    "pduTotal",
    "sampleTime",
    "totalValues",
    "vectorDimension"
})
public class GriddedDataPdu
    extends SyntheticEnvironmentFamilyPdu
{

    protected short constantGrid;
    protected int coordinateSystem;
    protected EntityType environmentType;
    protected EntityID environmentalSimulationApplicationID;
    protected int fieldNumber;
    @XmlElement(nillable = true)
    protected List<Object> gridDataList;
    protected short numberOfGridAxes;
    protected Orientation orientation;
    protected int padding1;
    protected short padding2;
    protected int pduNumber;
    protected int pduTotal;
    protected long sampleTime;
    protected long totalValues;
    protected short vectorDimension;

    /**
     * Gets the value of the constantGrid property.
     * 
     */
    public short getConstantGrid() {
        return constantGrid;
    }

    /**
     * Sets the value of the constantGrid property.
     * 
     */
    public void setConstantGrid(short value) {
        this.constantGrid = value;
    }

    /**
     * Gets the value of the coordinateSystem property.
     * 
     */
    public int getCoordinateSystem() {
        return coordinateSystem;
    }

    /**
     * Sets the value of the coordinateSystem property.
     * 
     */
    public void setCoordinateSystem(int value) {
        this.coordinateSystem = value;
    }

    /**
     * Gets the value of the environmentType property.
     * 
     * @return
     *     possible object is
     *     {@link EntityType }
     *     
     */
    public EntityType getEnvironmentType() {
        return environmentType;
    }

    /**
     * Sets the value of the environmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityType }
     *     
     */
    public void setEnvironmentType(EntityType value) {
        this.environmentType = value;
    }

    /**
     * Gets the value of the environmentalSimulationApplicationID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getEnvironmentalSimulationApplicationID() {
        return environmentalSimulationApplicationID;
    }

    /**
     * Sets the value of the environmentalSimulationApplicationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setEnvironmentalSimulationApplicationID(EntityID value) {
        this.environmentalSimulationApplicationID = value;
    }

    /**
     * Gets the value of the fieldNumber property.
     * 
     */
    public int getFieldNumber() {
        return fieldNumber;
    }

    /**
     * Sets the value of the fieldNumber property.
     * 
     */
    public void setFieldNumber(int value) {
        this.fieldNumber = value;
    }

    /**
     * Gets the value of the gridDataList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gridDataList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGridDataList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getGridDataList() {
        if (gridDataList == null) {
            gridDataList = new ArrayList<Object>();
        }
        return this.gridDataList;
    }

    /**
     * Gets the value of the numberOfGridAxes property.
     * 
     */
    public short getNumberOfGridAxes() {
        return numberOfGridAxes;
    }

    /**
     * Sets the value of the numberOfGridAxes property.
     * 
     */
    public void setNumberOfGridAxes(short value) {
        this.numberOfGridAxes = value;
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link Orientation }
     *     
     */
    public Orientation getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Orientation }
     *     
     */
    public void setOrientation(Orientation value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the padding1 property.
     * 
     */
    public int getPadding1() {
        return padding1;
    }

    /**
     * Sets the value of the padding1 property.
     * 
     */
    public void setPadding1(int value) {
        this.padding1 = value;
    }

    /**
     * Gets the value of the padding2 property.
     * 
     */
    public short getPadding2() {
        return padding2;
    }

    /**
     * Sets the value of the padding2 property.
     * 
     */
    public void setPadding2(short value) {
        this.padding2 = value;
    }

    /**
     * Gets the value of the pduNumber property.
     * 
     */
    public int getPduNumber() {
        return pduNumber;
    }

    /**
     * Sets the value of the pduNumber property.
     * 
     */
    public void setPduNumber(int value) {
        this.pduNumber = value;
    }

    /**
     * Gets the value of the pduTotal property.
     * 
     */
    public int getPduTotal() {
        return pduTotal;
    }

    /**
     * Sets the value of the pduTotal property.
     * 
     */
    public void setPduTotal(int value) {
        this.pduTotal = value;
    }

    /**
     * Gets the value of the sampleTime property.
     * 
     */
    public long getSampleTime() {
        return sampleTime;
    }

    /**
     * Sets the value of the sampleTime property.
     * 
     */
    public void setSampleTime(long value) {
        this.sampleTime = value;
    }

    /**
     * Gets the value of the totalValues property.
     * 
     */
    public long getTotalValues() {
        return totalValues;
    }

    /**
     * Sets the value of the totalValues property.
     * 
     */
    public void setTotalValues(long value) {
        this.totalValues = value;
    }

    /**
     * Gets the value of the vectorDimension property.
     * 
     */
    public short getVectorDimension() {
        return vectorDimension;
    }

    /**
     * Sets the value of the vectorDimension property.
     * 
     */
    public void setVectorDimension(short value) {
        this.vectorDimension = value;
    }

}
