//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for iffFundamentalData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="iffFundamentalData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alternateParameter4" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="informationLayers" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="modifier" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="parameter1" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="parameter2" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="parameter3" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="parameter4" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="parameter5" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="parameter6" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="systemStatus" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "iffFundamentalData", propOrder = {
    "alternateParameter4",
    "informationLayers",
    "modifier",
    "parameter1",
    "parameter2",
    "parameter3",
    "parameter4",
    "parameter5",
    "parameter6",
    "systemStatus"
})
public class IffFundamentalData {

    protected short alternateParameter4;
    protected short informationLayers;
    protected short modifier;
    protected int parameter1;
    protected int parameter2;
    protected int parameter3;
    protected int parameter4;
    protected int parameter5;
    protected int parameter6;
    protected short systemStatus;

    /**
     * Gets the value of the alternateParameter4 property.
     * 
     */
    public short getAlternateParameter4() {
        return alternateParameter4;
    }

    /**
     * Sets the value of the alternateParameter4 property.
     * 
     */
    public void setAlternateParameter4(short value) {
        this.alternateParameter4 = value;
    }

    /**
     * Gets the value of the informationLayers property.
     * 
     */
    public short getInformationLayers() {
        return informationLayers;
    }

    /**
     * Sets the value of the informationLayers property.
     * 
     */
    public void setInformationLayers(short value) {
        this.informationLayers = value;
    }

    /**
     * Gets the value of the modifier property.
     * 
     */
    public short getModifier() {
        return modifier;
    }

    /**
     * Sets the value of the modifier property.
     * 
     */
    public void setModifier(short value) {
        this.modifier = value;
    }

    /**
     * Gets the value of the parameter1 property.
     * 
     */
    public int getParameter1() {
        return parameter1;
    }

    /**
     * Sets the value of the parameter1 property.
     * 
     */
    public void setParameter1(int value) {
        this.parameter1 = value;
    }

    /**
     * Gets the value of the parameter2 property.
     * 
     */
    public int getParameter2() {
        return parameter2;
    }

    /**
     * Sets the value of the parameter2 property.
     * 
     */
    public void setParameter2(int value) {
        this.parameter2 = value;
    }

    /**
     * Gets the value of the parameter3 property.
     * 
     */
    public int getParameter3() {
        return parameter3;
    }

    /**
     * Sets the value of the parameter3 property.
     * 
     */
    public void setParameter3(int value) {
        this.parameter3 = value;
    }

    /**
     * Gets the value of the parameter4 property.
     * 
     */
    public int getParameter4() {
        return parameter4;
    }

    /**
     * Sets the value of the parameter4 property.
     * 
     */
    public void setParameter4(int value) {
        this.parameter4 = value;
    }

    /**
     * Gets the value of the parameter5 property.
     * 
     */
    public int getParameter5() {
        return parameter5;
    }

    /**
     * Sets the value of the parameter5 property.
     * 
     */
    public void setParameter5(int value) {
        this.parameter5 = value;
    }

    /**
     * Gets the value of the parameter6 property.
     * 
     */
    public int getParameter6() {
        return parameter6;
    }

    /**
     * Sets the value of the parameter6 property.
     * 
     */
    public void setParameter6(int value) {
        this.parameter6 = value;
    }

    /**
     * Gets the value of the systemStatus property.
     * 
     */
    public short getSystemStatus() {
        return systemStatus;
    }

    /**
     * Sets the value of the systemStatus property.
     * 
     */
    public void setSystemStatus(short value) {
        this.systemStatus = value;
    }

}
