//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for intercomCommunicationsParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="intercomCommunicationsParameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="recordLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="recordSpecificField" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="recordType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "intercomCommunicationsParameters", propOrder = {
    "recordLength",
    "recordSpecificField",
    "recordType"
})
public class IntercomCommunicationsParameters {

    protected int recordLength;
    protected long recordSpecificField;
    protected int recordType;

    /**
     * Gets the value of the recordLength property.
     * 
     */
    public int getRecordLength() {
        return recordLength;
    }

    /**
     * Sets the value of the recordLength property.
     * 
     */
    public void setRecordLength(int value) {
        this.recordLength = value;
    }

    /**
     * Gets the value of the recordSpecificField property.
     * 
     */
    public long getRecordSpecificField() {
        return recordSpecificField;
    }

    /**
     * Sets the value of the recordSpecificField property.
     * 
     */
    public void setRecordSpecificField(long value) {
        this.recordSpecificField = value;
    }

    /**
     * Gets the value of the recordType property.
     * 
     */
    public int getRecordType() {
        return recordType;
    }

    /**
     * Sets the value of the recordType property.
     * 
     */
    public void setRecordType(int value) {
        this.recordType = value;
    }

}
