//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for intercomSignalPdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="intercomSignalPdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}radioCommunicationsFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="communicationsDeviceID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dataLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="encodingScheme" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="entityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="sampleRate" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="samples" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tdlType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "intercomSignalPdu", propOrder = {
    "communicationsDeviceID",
    "data",
    "dataLength",
    "encodingScheme",
    "entityID",
    "sampleRate",
    "samples",
    "tdlType"
})
public class IntercomSignalPdu
    extends RadioCommunicationsFamilyPdu
{

    protected int communicationsDeviceID;
    @XmlElement(nillable = true)
    protected List<Object> data;
    protected int dataLength;
    protected int encodingScheme;
    protected EntityID entityID;
    protected long sampleRate;
    protected int samples;
    protected int tdlType;

    /**
     * Gets the value of the communicationsDeviceID property.
     * 
     */
    public int getCommunicationsDeviceID() {
        return communicationsDeviceID;
    }

    /**
     * Sets the value of the communicationsDeviceID property.
     * 
     */
    public void setCommunicationsDeviceID(int value) {
        this.communicationsDeviceID = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the data property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getData() {
        if (data == null) {
            data = new ArrayList<Object>();
        }
        return this.data;
    }

    /**
     * Gets the value of the dataLength property.
     * 
     */
    public int getDataLength() {
        return dataLength;
    }

    /**
     * Sets the value of the dataLength property.
     * 
     */
    public void setDataLength(int value) {
        this.dataLength = value;
    }

    /**
     * Gets the value of the encodingScheme property.
     * 
     */
    public int getEncodingScheme() {
        return encodingScheme;
    }

    /**
     * Sets the value of the encodingScheme property.
     * 
     */
    public void setEncodingScheme(int value) {
        this.encodingScheme = value;
    }

    /**
     * Gets the value of the entityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getEntityID() {
        return entityID;
    }

    /**
     * Sets the value of the entityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setEntityID(EntityID value) {
        this.entityID = value;
    }

    /**
     * Gets the value of the sampleRate property.
     * 
     */
    public long getSampleRate() {
        return sampleRate;
    }

    /**
     * Sets the value of the sampleRate property.
     * 
     */
    public void setSampleRate(long value) {
        this.sampleRate = value;
    }

    /**
     * Gets the value of the samples property.
     * 
     */
    public int getSamples() {
        return samples;
    }

    /**
     * Sets the value of the samples property.
     * 
     */
    public void setSamples(int value) {
        this.samples = value;
    }

    /**
     * Gets the value of the tdlType property.
     * 
     */
    public int getTdlType() {
        return tdlType;
    }

    /**
     * Sets the value of the tdlType property.
     * 
     */
    public void setTdlType(int value) {
        this.tdlType = value;
    }

}
