//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pdu">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="exerciseID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="padding" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="pduType" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="protocolFamily" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="protocolVersion" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pdu", propOrder = {
    "exerciseID",
    "length",
    "padding",
    "pduType",
    "protocolFamily",
    "protocolVersion",
    "timestamp"
})
@XmlSeeAlso({
    WarfareFamilyPdu.class,
    LogisticsFamilyPdu.class,
    DistributedEmissionsFamilyPdu.class,
    EntityManagementFamilyPdu.class,
    EntityInformationFamilyPdu.class,
    RadioCommunicationsFamilyPdu.class,
    SyntheticEnvironmentFamilyPdu.class,
    SimulationManagementFamilyPdu.class,
    MinefieldFamilyPdu.class,
    SimulationManagementWithReliabilityFamilyPdu.class
})
public class Pdu {

    protected short exerciseID;
    protected int length;
    protected short padding;
    protected short pduType;
    protected short protocolFamily;
    protected short protocolVersion;
    protected long timestamp;

    /**
     * Gets the value of the exerciseID property.
     * 
     */
    public short getExerciseID() {
        return exerciseID;
    }

    /**
     * Sets the value of the exerciseID property.
     * 
     */
    public void setExerciseID(short value) {
        this.exerciseID = value;
    }

    /**
     * Gets the value of the length property.
     * 
     */
    public int getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     */
    public void setLength(int value) {
        this.length = value;
    }

    /**
     * Gets the value of the padding property.
     * 
     */
    public short getPadding() {
        return padding;
    }

    /**
     * Sets the value of the padding property.
     * 
     */
    public void setPadding(short value) {
        this.padding = value;
    }

    /**
     * Gets the value of the pduType property.
     * 
     */
    public short getPduType() {
        return pduType;
    }

    /**
     * Sets the value of the pduType property.
     * 
     */
    public void setPduType(short value) {
        this.pduType = value;
    }

    /**
     * Gets the value of the protocolFamily property.
     * 
     */
    public short getProtocolFamily() {
        return protocolFamily;
    }

    /**
     * Sets the value of the protocolFamily property.
     * 
     */
    public void setProtocolFamily(short value) {
        this.protocolFamily = value;
    }

    /**
     * Gets the value of the protocolVersion property.
     * 
     */
    public short getProtocolVersion() {
        return protocolVersion;
    }

    /**
     * Sets the value of the protocolVersion property.
     * 
     */
    public void setProtocolVersion(short value) {
        this.protocolVersion = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     */
    public long getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     */
    public void setTimestamp(long value) {
        this.timestamp = value;
    }

}
