//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shaftRPMs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="shaftRPMs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="currentShaftRPMs" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="orderedShaftRPMs" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="shaftRPMRateOfChange" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "shaftRPMs", propOrder = {
    "currentShaftRPMs",
    "orderedShaftRPMs",
    "shaftRPMRateOfChange"
})
public class ShaftRPMs {

    protected short currentShaftRPMs;
    protected short orderedShaftRPMs;
    protected float shaftRPMRateOfChange;

    /**
     * Gets the value of the currentShaftRPMs property.
     * 
     */
    public short getCurrentShaftRPMs() {
        return currentShaftRPMs;
    }

    /**
     * Sets the value of the currentShaftRPMs property.
     * 
     */
    public void setCurrentShaftRPMs(short value) {
        this.currentShaftRPMs = value;
    }

    /**
     * Gets the value of the orderedShaftRPMs property.
     * 
     */
    public short getOrderedShaftRPMs() {
        return orderedShaftRPMs;
    }

    /**
     * Sets the value of the orderedShaftRPMs property.
     * 
     */
    public void setOrderedShaftRPMs(short value) {
        this.orderedShaftRPMs = value;
    }

    /**
     * Gets the value of the shaftRPMRateOfChange property.
     * 
     */
    public float getShaftRPMRateOfChange() {
        return shaftRPMRateOfChange;
    }

    /**
     * Sets the value of the shaftRPMRateOfChange property.
     * 
     */
    public void setShaftRPMRateOfChange(float value) {
        this.shaftRPMRateOfChange = value;
    }

}
