//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for trackJamTarget complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trackJamTarget">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="beamID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="emitterID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="trackJam" type="{}entityID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trackJamTarget", propOrder = {
    "beamID",
    "emitterID",
    "trackJam"
})
public class TrackJamTarget {

    protected short beamID;
    protected short emitterID;
    protected EntityID trackJam;

    /**
     * Gets the value of the beamID property.
     * 
     */
    public short getBeamID() {
        return beamID;
    }

    /**
     * Sets the value of the beamID property.
     * 
     */
    public void setBeamID(short value) {
        this.beamID = value;
    }

    /**
     * Gets the value of the emitterID property.
     * 
     */
    public short getEmitterID() {
        return emitterID;
    }

    /**
     * Sets the value of the emitterID property.
     * 
     */
    public void setEmitterID(short value) {
        this.emitterID = value;
    }

    /**
     * Gets the value of the trackJam property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getTrackJam() {
        return trackJam;
    }

    /**
     * Sets the value of the trackJam property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setTrackJam(EntityID value) {
        this.trackJam = value;
    }

}
