//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for uaPdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="uaPdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}distributedEmissionsFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="apaData" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="emitterSystems" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="emittingEntityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="eventID" type="{}eventID" minOccurs="0"/>
 *         &lt;element name="numberOfAPAs" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="numberOfShafts" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="numberOfUAEmitterSystems" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="pad" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="passiveParameterIndex" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="propulsionPlantConfiguration" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="shaftRPMs" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="stateChangeIndicator" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "uaPdu", propOrder = {
    "apaData",
    "emitterSystems",
    "emittingEntityID",
    "eventID",
    "numberOfAPAs",
    "numberOfShafts",
    "numberOfUAEmitterSystems",
    "pad",
    "passiveParameterIndex",
    "propulsionPlantConfiguration",
    "shaftRPMs",
    "stateChangeIndicator"
})
public class UaPdu
    extends DistributedEmissionsFamilyPdu
{

    @XmlElement(nillable = true)
    protected List<Object> apaData;
    @XmlElement(nillable = true)
    protected List<Object> emitterSystems;
    protected EntityID emittingEntityID;
    protected EventID eventID;
    protected short numberOfAPAs;
    protected short numberOfShafts;
    protected short numberOfUAEmitterSystems;
    protected byte pad;
    protected int passiveParameterIndex;
    protected short propulsionPlantConfiguration;
    @XmlElement(nillable = true)
    protected List<Object> shaftRPMs;
    protected byte stateChangeIndicator;

    /**
     * Gets the value of the apaData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the apaData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApaData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getApaData() {
        if (apaData == null) {
            apaData = new ArrayList<Object>();
        }
        return this.apaData;
    }

    /**
     * Gets the value of the emitterSystems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emitterSystems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmitterSystems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getEmitterSystems() {
        if (emitterSystems == null) {
            emitterSystems = new ArrayList<Object>();
        }
        return this.emitterSystems;
    }

    /**
     * Gets the value of the emittingEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getEmittingEntityID() {
        return emittingEntityID;
    }

    /**
     * Sets the value of the emittingEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setEmittingEntityID(EntityID value) {
        this.emittingEntityID = value;
    }

    /**
     * Gets the value of the eventID property.
     * 
     * @return
     *     possible object is
     *     {@link EventID }
     *     
     */
    public EventID getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventID }
     *     
     */
    public void setEventID(EventID value) {
        this.eventID = value;
    }

    /**
     * Gets the value of the numberOfAPAs property.
     * 
     */
    public short getNumberOfAPAs() {
        return numberOfAPAs;
    }

    /**
     * Sets the value of the numberOfAPAs property.
     * 
     */
    public void setNumberOfAPAs(short value) {
        this.numberOfAPAs = value;
    }

    /**
     * Gets the value of the numberOfShafts property.
     * 
     */
    public short getNumberOfShafts() {
        return numberOfShafts;
    }

    /**
     * Sets the value of the numberOfShafts property.
     * 
     */
    public void setNumberOfShafts(short value) {
        this.numberOfShafts = value;
    }

    /**
     * Gets the value of the numberOfUAEmitterSystems property.
     * 
     */
    public short getNumberOfUAEmitterSystems() {
        return numberOfUAEmitterSystems;
    }

    /**
     * Sets the value of the numberOfUAEmitterSystems property.
     * 
     */
    public void setNumberOfUAEmitterSystems(short value) {
        this.numberOfUAEmitterSystems = value;
    }

    /**
     * Gets the value of the pad property.
     * 
     */
    public byte getPad() {
        return pad;
    }

    /**
     * Sets the value of the pad property.
     * 
     */
    public void setPad(byte value) {
        this.pad = value;
    }

    /**
     * Gets the value of the passiveParameterIndex property.
     * 
     */
    public int getPassiveParameterIndex() {
        return passiveParameterIndex;
    }

    /**
     * Sets the value of the passiveParameterIndex property.
     * 
     */
    public void setPassiveParameterIndex(int value) {
        this.passiveParameterIndex = value;
    }

    /**
     * Gets the value of the propulsionPlantConfiguration property.
     * 
     */
    public short getPropulsionPlantConfiguration() {
        return propulsionPlantConfiguration;
    }

    /**
     * Sets the value of the propulsionPlantConfiguration property.
     * 
     */
    public void setPropulsionPlantConfiguration(short value) {
        this.propulsionPlantConfiguration = value;
    }

    /**
     * Gets the value of the shaftRPMs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shaftRPMs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShaftRPMs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getShaftRPMs() {
        if (shaftRPMs == null) {
            shaftRPMs = new ArrayList<Object>();
        }
        return this.shaftRPMs;
    }

    /**
     * Gets the value of the stateChangeIndicator property.
     * 
     */
    public byte getStateChangeIndicator() {
        return stateChangeIndicator;
    }

    /**
     * Sets the value of the stateChangeIndicator property.
     * 
     */
    public void setStateChangeIndicator(byte value) {
        this.stateChangeIndicator = value;
    }

}
