//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for collisionPdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="collisionPdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}entityInformationFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="collidingEntityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="collisionType" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="eventID" type="{}eventID" minOccurs="0"/>
 *         &lt;element name="issuingEntityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="location" type="{}vector3Float" minOccurs="0"/>
 *         &lt;element name="mass" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="pad" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="velocity" type="{}vector3Float" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "collisionPdu", propOrder = {
    "collidingEntityID",
    "collisionType",
    "eventID",
    "issuingEntityID",
    "location",
    "mass",
    "pad",
    "velocity"
})
public class CollisionPdu
    extends EntityInformationFamilyPdu
{

    protected EntityID collidingEntityID;
    protected short collisionType;
    protected EventID eventID;
    protected EntityID issuingEntityID;
    protected Vector3Float location;
    protected float mass;
    protected byte pad;
    protected Vector3Float velocity;

    /**
     * Gets the value of the collidingEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getCollidingEntityID() {
        return collidingEntityID;
    }

    /**
     * Sets the value of the collidingEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setCollidingEntityID(EntityID value) {
        this.collidingEntityID = value;
    }

    /**
     * Gets the value of the collisionType property.
     * 
     */
    public short getCollisionType() {
        return collisionType;
    }

    /**
     * Sets the value of the collisionType property.
     * 
     */
    public void setCollisionType(short value) {
        this.collisionType = value;
    }

    /**
     * Gets the value of the eventID property.
     * 
     * @return
     *     possible object is
     *     {@link EventID }
     *     
     */
    public EventID getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventID }
     *     
     */
    public void setEventID(EventID value) {
        this.eventID = value;
    }

    /**
     * Gets the value of the issuingEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getIssuingEntityID() {
        return issuingEntityID;
    }

    /**
     * Sets the value of the issuingEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setIssuingEntityID(EntityID value) {
        this.issuingEntityID = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Float }
     *     
     */
    public Vector3Float getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Float }
     *     
     */
    public void setLocation(Vector3Float value) {
        this.location = value;
    }

    /**
     * Gets the value of the mass property.
     * 
     */
    public float getMass() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     */
    public void setMass(float value) {
        this.mass = value;
    }

    /**
     * Gets the value of the pad property.
     * 
     */
    public byte getPad() {
        return pad;
    }

    /**
     * Sets the value of the pad property.
     * 
     */
    public void setPad(byte value) {
        this.pad = value;
    }

    /**
     * Gets the value of the velocity property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Float }
     *     
     */
    public Vector3Float getVelocity() {
        return velocity;
    }

    /**
     * Sets the value of the velocity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Float }
     *     
     */
    public void setVelocity(Vector3Float value) {
        this.velocity = value;
    }

}
