//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for collisionElasticPdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="collisionElasticPdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}entityInformationFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="coefficientOfRestitution" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="collidingEntityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="collisionEventID" type="{}eventID" minOccurs="0"/>
 *         &lt;element name="collisionResultXX" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="collisionResultXY" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="collisionResultXZ" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="collisionResultYY" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="collisionResultYZ" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="collisionResultZZ" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="contactVelocity" type="{}vector3Float" minOccurs="0"/>
 *         &lt;element name="issuingEntityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="location" type="{}vector3Float" minOccurs="0"/>
 *         &lt;element name="mass" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="pad" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="unitSurfaceNormal" type="{}vector3Float" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "collisionElasticPdu", propOrder = {
    "coefficientOfRestitution",
    "collidingEntityID",
    "collisionEventID",
    "collisionResultXX",
    "collisionResultXY",
    "collisionResultXZ",
    "collisionResultYY",
    "collisionResultYZ",
    "collisionResultZZ",
    "contactVelocity",
    "issuingEntityID",
    "location",
    "mass",
    "pad",
    "unitSurfaceNormal"
})
public class CollisionElasticPdu
    extends EntityInformationFamilyPdu
{

    protected float coefficientOfRestitution;
    protected EntityID collidingEntityID;
    protected EventID collisionEventID;
    protected float collisionResultXX;
    protected float collisionResultXY;
    protected float collisionResultXZ;
    protected float collisionResultYY;
    protected float collisionResultYZ;
    protected float collisionResultZZ;
    protected Vector3Float contactVelocity;
    protected EntityID issuingEntityID;
    protected Vector3Float location;
    protected float mass;
    protected short pad;
    protected Vector3Float unitSurfaceNormal;

    /**
     * Gets the value of the coefficientOfRestitution property.
     * 
     */
    public float getCoefficientOfRestitution() {
        return coefficientOfRestitution;
    }

    /**
     * Sets the value of the coefficientOfRestitution property.
     * 
     */
    public void setCoefficientOfRestitution(float value) {
        this.coefficientOfRestitution = value;
    }

    /**
     * Gets the value of the collidingEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getCollidingEntityID() {
        return collidingEntityID;
    }

    /**
     * Sets the value of the collidingEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setCollidingEntityID(EntityID value) {
        this.collidingEntityID = value;
    }

    /**
     * Gets the value of the collisionEventID property.
     * 
     * @return
     *     possible object is
     *     {@link EventID }
     *     
     */
    public EventID getCollisionEventID() {
        return collisionEventID;
    }

    /**
     * Sets the value of the collisionEventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventID }
     *     
     */
    public void setCollisionEventID(EventID value) {
        this.collisionEventID = value;
    }

    /**
     * Gets the value of the collisionResultXX property.
     * 
     */
    public float getCollisionResultXX() {
        return collisionResultXX;
    }

    /**
     * Sets the value of the collisionResultXX property.
     * 
     */
    public void setCollisionResultXX(float value) {
        this.collisionResultXX = value;
    }

    /**
     * Gets the value of the collisionResultXY property.
     * 
     */
    public float getCollisionResultXY() {
        return collisionResultXY;
    }

    /**
     * Sets the value of the collisionResultXY property.
     * 
     */
    public void setCollisionResultXY(float value) {
        this.collisionResultXY = value;
    }

    /**
     * Gets the value of the collisionResultXZ property.
     * 
     */
    public float getCollisionResultXZ() {
        return collisionResultXZ;
    }

    /**
     * Sets the value of the collisionResultXZ property.
     * 
     */
    public void setCollisionResultXZ(float value) {
        this.collisionResultXZ = value;
    }

    /**
     * Gets the value of the collisionResultYY property.
     * 
     */
    public float getCollisionResultYY() {
        return collisionResultYY;
    }

    /**
     * Sets the value of the collisionResultYY property.
     * 
     */
    public void setCollisionResultYY(float value) {
        this.collisionResultYY = value;
    }

    /**
     * Gets the value of the collisionResultYZ property.
     * 
     */
    public float getCollisionResultYZ() {
        return collisionResultYZ;
    }

    /**
     * Sets the value of the collisionResultYZ property.
     * 
     */
    public void setCollisionResultYZ(float value) {
        this.collisionResultYZ = value;
    }

    /**
     * Gets the value of the collisionResultZZ property.
     * 
     */
    public float getCollisionResultZZ() {
        return collisionResultZZ;
    }

    /**
     * Sets the value of the collisionResultZZ property.
     * 
     */
    public void setCollisionResultZZ(float value) {
        this.collisionResultZZ = value;
    }

    /**
     * Gets the value of the contactVelocity property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Float }
     *     
     */
    public Vector3Float getContactVelocity() {
        return contactVelocity;
    }

    /**
     * Sets the value of the contactVelocity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Float }
     *     
     */
    public void setContactVelocity(Vector3Float value) {
        this.contactVelocity = value;
    }

    /**
     * Gets the value of the issuingEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getIssuingEntityID() {
        return issuingEntityID;
    }

    /**
     * Sets the value of the issuingEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setIssuingEntityID(EntityID value) {
        this.issuingEntityID = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Float }
     *     
     */
    public Vector3Float getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Float }
     *     
     */
    public void setLocation(Vector3Float value) {
        this.location = value;
    }

    /**
     * Gets the value of the mass property.
     * 
     */
    public float getMass() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     */
    public void setMass(float value) {
        this.mass = value;
    }

    /**
     * Gets the value of the pad property.
     * 
     */
    public short getPad() {
        return pad;
    }

    /**
     * Sets the value of the pad property.
     * 
     */
    public void setPad(short value) {
        this.pad = value;
    }

    /**
     * Gets the value of the unitSurfaceNormal property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Float }
     *     
     */
    public Vector3Float getUnitSurfaceNormal() {
        return unitSurfaceNormal;
    }

    /**
     * Sets the value of the unitSurfaceNormal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Float }
     *     
     */
    public void setUnitSurfaceNormal(Vector3Float value) {
        this.unitSurfaceNormal = value;
    }

}
