//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for designatorPdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="designatorPdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}distributedEmissionsFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="codeName" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="deadReckoningAlgorithm" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="designatedEntityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="designatingEntityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="designatorCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="designatorPower" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="designatorSpotLocation" type="{}vector3Double" minOccurs="0"/>
 *         &lt;element name="designatorSpotWrtDesignated" type="{}vector3Float" minOccurs="0"/>
 *         &lt;element name="designatorWavelength" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="entityLinearAcceleration" type="{}vector3Float" minOccurs="0"/>
 *         &lt;element name="padding1" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="padding2" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "designatorPdu", propOrder = {
    "codeName",
    "deadReckoningAlgorithm",
    "designatedEntityID",
    "designatingEntityID",
    "designatorCode",
    "designatorPower",
    "designatorSpotLocation",
    "designatorSpotWrtDesignated",
    "designatorWavelength",
    "entityLinearAcceleration",
    "padding1",
    "padding2"
})
public class DesignatorPdu
    extends DistributedEmissionsFamilyPdu
{

    protected int codeName;
    protected byte deadReckoningAlgorithm;
    protected EntityID designatedEntityID;
    protected EntityID designatingEntityID;
    protected int designatorCode;
    protected float designatorPower;
    protected Vector3Double designatorSpotLocation;
    protected Vector3Float designatorSpotWrtDesignated;
    protected float designatorWavelength;
    protected Vector3Float entityLinearAcceleration;
    protected int padding1;
    protected byte padding2;

    /**
     * Gets the value of the codeName property.
     * 
     */
    public int getCodeName() {
        return codeName;
    }

    /**
     * Sets the value of the codeName property.
     * 
     */
    public void setCodeName(int value) {
        this.codeName = value;
    }

    /**
     * Gets the value of the deadReckoningAlgorithm property.
     * 
     */
    public byte getDeadReckoningAlgorithm() {
        return deadReckoningAlgorithm;
    }

    /**
     * Sets the value of the deadReckoningAlgorithm property.
     * 
     */
    public void setDeadReckoningAlgorithm(byte value) {
        this.deadReckoningAlgorithm = value;
    }

    /**
     * Gets the value of the designatedEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getDesignatedEntityID() {
        return designatedEntityID;
    }

    /**
     * Sets the value of the designatedEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setDesignatedEntityID(EntityID value) {
        this.designatedEntityID = value;
    }

    /**
     * Gets the value of the designatingEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getDesignatingEntityID() {
        return designatingEntityID;
    }

    /**
     * Sets the value of the designatingEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setDesignatingEntityID(EntityID value) {
        this.designatingEntityID = value;
    }

    /**
     * Gets the value of the designatorCode property.
     * 
     */
    public int getDesignatorCode() {
        return designatorCode;
    }

    /**
     * Sets the value of the designatorCode property.
     * 
     */
    public void setDesignatorCode(int value) {
        this.designatorCode = value;
    }

    /**
     * Gets the value of the designatorPower property.
     * 
     */
    public float getDesignatorPower() {
        return designatorPower;
    }

    /**
     * Sets the value of the designatorPower property.
     * 
     */
    public void setDesignatorPower(float value) {
        this.designatorPower = value;
    }

    /**
     * Gets the value of the designatorSpotLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Double }
     *     
     */
    public Vector3Double getDesignatorSpotLocation() {
        return designatorSpotLocation;
    }

    /**
     * Sets the value of the designatorSpotLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Double }
     *     
     */
    public void setDesignatorSpotLocation(Vector3Double value) {
        this.designatorSpotLocation = value;
    }

    /**
     * Gets the value of the designatorSpotWrtDesignated property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Float }
     *     
     */
    public Vector3Float getDesignatorSpotWrtDesignated() {
        return designatorSpotWrtDesignated;
    }

    /**
     * Sets the value of the designatorSpotWrtDesignated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Float }
     *     
     */
    public void setDesignatorSpotWrtDesignated(Vector3Float value) {
        this.designatorSpotWrtDesignated = value;
    }

    /**
     * Gets the value of the designatorWavelength property.
     * 
     */
    public float getDesignatorWavelength() {
        return designatorWavelength;
    }

    /**
     * Sets the value of the designatorWavelength property.
     * 
     */
    public void setDesignatorWavelength(float value) {
        this.designatorWavelength = value;
    }

    /**
     * Gets the value of the entityLinearAcceleration property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Float }
     *     
     */
    public Vector3Float getEntityLinearAcceleration() {
        return entityLinearAcceleration;
    }

    /**
     * Sets the value of the entityLinearAcceleration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Float }
     *     
     */
    public void setEntityLinearAcceleration(Vector3Float value) {
        this.entityLinearAcceleration = value;
    }

    /**
     * Gets the value of the padding1 property.
     * 
     */
    public int getPadding1() {
        return padding1;
    }

    /**
     * Sets the value of the padding1 property.
     * 
     */
    public void setPadding1(int value) {
        this.padding1 = value;
    }

    /**
     * Gets the value of the padding2 property.
     * 
     */
    public byte getPadding2() {
        return padding2;
    }

    /**
     * Sets the value of the padding2 property.
     * 
     */
    public void setPadding2(byte value) {
        this.padding2 = value;
    }

}
