//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fundamentalParameterDataIff complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fundamentalParameterDataIff">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="applicableModes" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="burstLength" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="erp" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="frequency" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="pad2" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pad3" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="pgrf" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="pulseWidth" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fundamentalParameterDataIff", propOrder = {
    "applicableModes",
    "burstLength",
    "erp",
    "frequency",
    "pad2",
    "pad3",
    "pgrf",
    "pulseWidth"
})
public class FundamentalParameterDataIff {

    protected short applicableModes;
    protected long burstLength;
    protected float erp;
    protected float frequency;
    protected int pad2;
    protected short pad3;
    protected float pgrf;
    protected float pulseWidth;

    /**
     * Gets the value of the applicableModes property.
     * 
     */
    public short getApplicableModes() {
        return applicableModes;
    }

    /**
     * Sets the value of the applicableModes property.
     * 
     */
    public void setApplicableModes(short value) {
        this.applicableModes = value;
    }

    /**
     * Gets the value of the burstLength property.
     * 
     */
    public long getBurstLength() {
        return burstLength;
    }

    /**
     * Sets the value of the burstLength property.
     * 
     */
    public void setBurstLength(long value) {
        this.burstLength = value;
    }

    /**
     * Gets the value of the erp property.
     * 
     */
    public float getErp() {
        return erp;
    }

    /**
     * Sets the value of the erp property.
     * 
     */
    public void setErp(float value) {
        this.erp = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     */
    public float getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     */
    public void setFrequency(float value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the pad2 property.
     * 
     */
    public int getPad2() {
        return pad2;
    }

    /**
     * Sets the value of the pad2 property.
     * 
     */
    public void setPad2(int value) {
        this.pad2 = value;
    }

    /**
     * Gets the value of the pad3 property.
     * 
     */
    public short getPad3() {
        return pad3;
    }

    /**
     * Sets the value of the pad3 property.
     * 
     */
    public void setPad3(short value) {
        this.pad3 = value;
    }

    /**
     * Gets the value of the pgrf property.
     * 
     */
    public float getPgrf() {
        return pgrf;
    }

    /**
     * Sets the value of the pgrf property.
     * 
     */
    public void setPgrf(float value) {
        this.pgrf = value;
    }

    /**
     * Gets the value of the pulseWidth property.
     * 
     */
    public float getPulseWidth() {
        return pulseWidth;
    }

    /**
     * Sets the value of the pulseWidth property.
     * 
     */
    public void setPulseWidth(float value) {
        this.pulseWidth = value;
    }

}
