//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for intercomControlPdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="intercomControlPdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}radioCommunicationsFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="command" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="communicationsChannelType" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="controlType" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="intercomParameters" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="intercomParametersLength" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="masterCommunicationsDeviceID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="masterEntityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="sourceCommunicationsDeviceID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="sourceEntityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="sourceLineID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="transmitLineState" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="transmitPriority" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "intercomControlPdu", propOrder = {
    "command",
    "communicationsChannelType",
    "controlType",
    "intercomParameters",
    "intercomParametersLength",
    "masterCommunicationsDeviceID",
    "masterEntityID",
    "sourceCommunicationsDeviceID",
    "sourceEntityID",
    "sourceLineID",
    "transmitLineState",
    "transmitPriority"
})
public class IntercomControlPdu
    extends RadioCommunicationsFamilyPdu
{

    protected short command;
    protected short communicationsChannelType;
    protected short controlType;
    @XmlElement(nillable = true)
    protected List<Object> intercomParameters;
    protected long intercomParametersLength;
    protected int masterCommunicationsDeviceID;
    protected EntityID masterEntityID;
    protected short sourceCommunicationsDeviceID;
    protected EntityID sourceEntityID;
    protected short sourceLineID;
    protected short transmitLineState;
    protected short transmitPriority;

    /**
     * Gets the value of the command property.
     * 
     */
    public short getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     */
    public void setCommand(short value) {
        this.command = value;
    }

    /**
     * Gets the value of the communicationsChannelType property.
     * 
     */
    public short getCommunicationsChannelType() {
        return communicationsChannelType;
    }

    /**
     * Sets the value of the communicationsChannelType property.
     * 
     */
    public void setCommunicationsChannelType(short value) {
        this.communicationsChannelType = value;
    }

    /**
     * Gets the value of the controlType property.
     * 
     */
    public short getControlType() {
        return controlType;
    }

    /**
     * Sets the value of the controlType property.
     * 
     */
    public void setControlType(short value) {
        this.controlType = value;
    }

    /**
     * Gets the value of the intercomParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the intercomParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIntercomParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getIntercomParameters() {
        if (intercomParameters == null) {
            intercomParameters = new ArrayList<Object>();
        }
        return this.intercomParameters;
    }

    /**
     * Gets the value of the intercomParametersLength property.
     * 
     */
    public long getIntercomParametersLength() {
        return intercomParametersLength;
    }

    /**
     * Sets the value of the intercomParametersLength property.
     * 
     */
    public void setIntercomParametersLength(long value) {
        this.intercomParametersLength = value;
    }

    /**
     * Gets the value of the masterCommunicationsDeviceID property.
     * 
     */
    public int getMasterCommunicationsDeviceID() {
        return masterCommunicationsDeviceID;
    }

    /**
     * Sets the value of the masterCommunicationsDeviceID property.
     * 
     */
    public void setMasterCommunicationsDeviceID(int value) {
        this.masterCommunicationsDeviceID = value;
    }

    /**
     * Gets the value of the masterEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getMasterEntityID() {
        return masterEntityID;
    }

    /**
     * Sets the value of the masterEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setMasterEntityID(EntityID value) {
        this.masterEntityID = value;
    }

    /**
     * Gets the value of the sourceCommunicationsDeviceID property.
     * 
     */
    public short getSourceCommunicationsDeviceID() {
        return sourceCommunicationsDeviceID;
    }

    /**
     * Sets the value of the sourceCommunicationsDeviceID property.
     * 
     */
    public void setSourceCommunicationsDeviceID(short value) {
        this.sourceCommunicationsDeviceID = value;
    }

    /**
     * Gets the value of the sourceEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getSourceEntityID() {
        return sourceEntityID;
    }

    /**
     * Sets the value of the sourceEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setSourceEntityID(EntityID value) {
        this.sourceEntityID = value;
    }

    /**
     * Gets the value of the sourceLineID property.
     * 
     */
    public short getSourceLineID() {
        return sourceLineID;
    }

    /**
     * Sets the value of the sourceLineID property.
     * 
     */
    public void setSourceLineID(short value) {
        this.sourceLineID = value;
    }

    /**
     * Gets the value of the transmitLineState property.
     * 
     */
    public short getTransmitLineState() {
        return transmitLineState;
    }

    /**
     * Sets the value of the transmitLineState property.
     * 
     */
    public void setTransmitLineState(short value) {
        this.transmitLineState = value;
    }

    /**
     * Gets the value of the transmitPriority property.
     * 
     */
    public short getTransmitPriority() {
        return transmitPriority;
    }

    /**
     * Sets the value of the transmitPriority property.
     * 
     */
    public void setTransmitPriority(short value) {
        this.transmitPriority = value;
    }

}
