//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for minefieldQueryPdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="minefieldQueryPdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}minefieldFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="dataFilter" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="minefieldID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="numberOfPerimeterPoints" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="numberOfSensorTypes" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="pad2" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="requestID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="requestedMineType" type="{}entityType" minOccurs="0"/>
 *         &lt;element name="requestedPerimeterPoints" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="requestingEntityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="sensorTypes" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "minefieldQueryPdu", propOrder = {
    "dataFilter",
    "minefieldID",
    "numberOfPerimeterPoints",
    "numberOfSensorTypes",
    "pad2",
    "requestID",
    "requestedMineType",
    "requestedPerimeterPoints",
    "requestingEntityID",
    "sensorTypes"
})
public class MinefieldQueryPdu
    extends MinefieldFamilyPdu
{

    protected long dataFilter;
    protected EntityID minefieldID;
    protected short numberOfPerimeterPoints;
    protected short numberOfSensorTypes;
    protected short pad2;
    protected short requestID;
    protected EntityType requestedMineType;
    @XmlElement(nillable = true)
    protected List<Object> requestedPerimeterPoints;
    protected EntityID requestingEntityID;
    @XmlElement(nillable = true)
    protected List<Object> sensorTypes;

    /**
     * Gets the value of the dataFilter property.
     * 
     */
    public long getDataFilter() {
        return dataFilter;
    }

    /**
     * Sets the value of the dataFilter property.
     * 
     */
    public void setDataFilter(long value) {
        this.dataFilter = value;
    }

    /**
     * Gets the value of the minefieldID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getMinefieldID() {
        return minefieldID;
    }

    /**
     * Sets the value of the minefieldID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setMinefieldID(EntityID value) {
        this.minefieldID = value;
    }

    /**
     * Gets the value of the numberOfPerimeterPoints property.
     * 
     */
    public short getNumberOfPerimeterPoints() {
        return numberOfPerimeterPoints;
    }

    /**
     * Sets the value of the numberOfPerimeterPoints property.
     * 
     */
    public void setNumberOfPerimeterPoints(short value) {
        this.numberOfPerimeterPoints = value;
    }

    /**
     * Gets the value of the numberOfSensorTypes property.
     * 
     */
    public short getNumberOfSensorTypes() {
        return numberOfSensorTypes;
    }

    /**
     * Sets the value of the numberOfSensorTypes property.
     * 
     */
    public void setNumberOfSensorTypes(short value) {
        this.numberOfSensorTypes = value;
    }

    /**
     * Gets the value of the pad2 property.
     * 
     */
    public short getPad2() {
        return pad2;
    }

    /**
     * Sets the value of the pad2 property.
     * 
     */
    public void setPad2(short value) {
        this.pad2 = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     */
    public short getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     */
    public void setRequestID(short value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the requestedMineType property.
     * 
     * @return
     *     possible object is
     *     {@link EntityType }
     *     
     */
    public EntityType getRequestedMineType() {
        return requestedMineType;
    }

    /**
     * Sets the value of the requestedMineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityType }
     *     
     */
    public void setRequestedMineType(EntityType value) {
        this.requestedMineType = value;
    }

    /**
     * Gets the value of the requestedPerimeterPoints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestedPerimeterPoints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestedPerimeterPoints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getRequestedPerimeterPoints() {
        if (requestedPerimeterPoints == null) {
            requestedPerimeterPoints = new ArrayList<Object>();
        }
        return this.requestedPerimeterPoints;
    }

    /**
     * Gets the value of the requestingEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getRequestingEntityID() {
        return requestingEntityID;
    }

    /**
     * Sets the value of the requestingEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setRequestingEntityID(EntityID value) {
        this.requestingEntityID = value;
    }

    /**
     * Gets the value of the sensorTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensorTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensorTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getSensorTypes() {
        if (sensorTypes == null) {
            sensorTypes = new ArrayList<Object>();
        }
        return this.sensorTypes;
    }

}
