//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.nps.moves.jaxb.dis package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.nps.moves.jaxb.dis
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AcousticBeamData }
     * 
     */
    public AcousticBeamData createAcousticBeamData() {
        return new AcousticBeamData();
    }

    /**
     * Create an instance of {@link GridAxisRecordRepresentation0 }
     * 
     */
    public GridAxisRecordRepresentation0 createGridAxisRecordRepresentation0() {
        return new GridAxisRecordRepresentation0();
    }

    /**
     * Create an instance of {@link IffAtcNavAidsLayer2Pdu }
     * 
     */
    public IffAtcNavAidsLayer2Pdu createIffAtcNavAidsLayer2Pdu() {
        return new IffAtcNavAidsLayer2Pdu();
    }

    /**
     * Create an instance of {@link TransmitterPdu }
     * 
     */
    public TransmitterPdu createTransmitterPdu() {
        return new TransmitterPdu();
    }

    /**
     * Create an instance of {@link MinefieldStatePdu }
     * 
     */
    public MinefieldStatePdu createMinefieldStatePdu() {
        return new MinefieldStatePdu();
    }

    /**
     * Create an instance of {@link ResupplyCancelPdu }
     * 
     */
    public ResupplyCancelPdu createResupplyCancelPdu() {
        return new ResupplyCancelPdu();
    }

    /**
     * Create an instance of {@link DataQueryPdu }
     * 
     */
    public DataQueryPdu createDataQueryPdu() {
        return new DataQueryPdu();
    }

    /**
     * Create an instance of {@link AggregateID }
     * 
     */
    public AggregateID createAggregateID() {
        return new AggregateID();
    }

    /**
     * Create an instance of {@link RecordQueryReliablePdu }
     * 
     */
    public RecordQueryReliablePdu createRecordQueryReliablePdu() {
        return new RecordQueryReliablePdu();
    }

    /**
     * Create an instance of {@link SimulationManagementWithReliabilityFamilyPdu }
     * 
     */
    public SimulationManagementWithReliabilityFamilyPdu createSimulationManagementWithReliabilityFamilyPdu() {
        return new SimulationManagementWithReliabilityFamilyPdu();
    }

    /**
     * Create an instance of {@link FundamentalParameterData }
     * 
     */
    public FundamentalParameterData createFundamentalParameterData() {
        return new FundamentalParameterData();
    }

    /**
     * Create an instance of {@link EntityInformationFamilyPdu }
     * 
     */
    public EntityInformationFamilyPdu createEntityInformationFamilyPdu() {
        return new EntityInformationFamilyPdu();
    }

    /**
     * Create an instance of {@link ResupplyReceivedPdu }
     * 
     */
    public ResupplyReceivedPdu createResupplyReceivedPdu() {
        return new ResupplyReceivedPdu();
    }

    /**
     * Create an instance of {@link UaPdu }
     * 
     */
    public UaPdu createUaPdu() {
        return new UaPdu();
    }

    /**
     * Create an instance of {@link MinefieldQueryPdu }
     * 
     */
    public MinefieldQueryPdu createMinefieldQueryPdu() {
        return new MinefieldQueryPdu();
    }

    /**
     * Create an instance of {@link RepairCompletePdu }
     * 
     */
    public RepairCompletePdu createRepairCompletePdu() {
        return new RepairCompletePdu();
    }

    /**
     * Create an instance of {@link ServiceRequestPdu }
     * 
     */
    public ServiceRequestPdu createServiceRequestPdu() {
        return new ServiceRequestPdu();
    }

    /**
     * Create an instance of {@link FixedDatum }
     * 
     */
    public FixedDatum createFixedDatum() {
        return new FixedDatum();
    }

    /**
     * Create an instance of {@link EventReportReliablePdu }
     * 
     */
    public EventReportReliablePdu createEventReportReliablePdu() {
        return new EventReportReliablePdu();
    }

    /**
     * Create an instance of {@link BeamData }
     * 
     */
    public BeamData createBeamData() {
        return new BeamData();
    }

    /**
     * Create an instance of {@link SixByteChunk }
     * 
     */
    public SixByteChunk createSixByteChunk() {
        return new SixByteChunk();
    }

    /**
     * Create an instance of {@link AggregateStatePdu }
     * 
     */
    public AggregateStatePdu createAggregateStatePdu() {
        return new AggregateStatePdu();
    }

    /**
     * Create an instance of {@link PropulsionSystemData }
     * 
     */
    public PropulsionSystemData createPropulsionSystemData() {
        return new PropulsionSystemData();
    }

    /**
     * Create an instance of {@link EightByteChunk }
     * 
     */
    public EightByteChunk createEightByteChunk() {
        return new EightByteChunk();
    }

    /**
     * Create an instance of {@link SetDataPdu }
     * 
     */
    public SetDataPdu createSetDataPdu() {
        return new SetDataPdu();
    }

    /**
     * Create an instance of {@link OneByteChunk }
     * 
     */
    public OneByteChunk createOneByteChunk() {
        return new OneByteChunk();
    }

    /**
     * Create an instance of {@link AcknowledgeReliablePdu }
     * 
     */
    public AcknowledgeReliablePdu createAcknowledgeReliablePdu() {
        return new AcknowledgeReliablePdu();
    }

    /**
     * Create an instance of {@link IntercomCommunicationsParameters }
     * 
     */
    public IntercomCommunicationsParameters createIntercomCommunicationsParameters() {
        return new IntercomCommunicationsParameters();
    }

    /**
     * Create an instance of {@link DetonationPdu }
     * 
     */
    public DetonationPdu createDetonationPdu() {
        return new DetonationPdu();
    }

    /**
     * Create an instance of {@link PduCollection }
     * 
     */
    public PduCollection createPduCollection() {
        return new PduCollection();
    }

    /**
     * Create an instance of {@link RadioEntityType }
     * 
     */
    public RadioEntityType createRadioEntityType() {
        return new RadioEntityType();
    }

    /**
     * Create an instance of {@link RemoveEntityReliablePdu }
     * 
     */
    public RemoveEntityReliablePdu createRemoveEntityReliablePdu() {
        return new RemoveEntityReliablePdu();
    }

    /**
     * Create an instance of {@link CommentReliablePdu }
     * 
     */
    public CommentReliablePdu createCommentReliablePdu() {
        return new CommentReliablePdu();
    }

    /**
     * Create an instance of {@link PointObjectStatePdu }
     * 
     */
    public PointObjectStatePdu createPointObjectStatePdu() {
        return new PointObjectStatePdu();
    }

    /**
     * Create an instance of {@link Environment }
     * 
     */
    public Environment createEnvironment() {
        return new Environment();
    }

    /**
     * Create an instance of {@link StartResumeReliablePdu }
     * 
     */
    public StartResumeReliablePdu createStartResumeReliablePdu() {
        return new StartResumeReliablePdu();
    }

    /**
     * Create an instance of {@link LinearSegmentParameter }
     * 
     */
    public LinearSegmentParameter createLinearSegmentParameter() {
        return new LinearSegmentParameter();
    }

    /**
     * Create an instance of {@link ArealObjectStatePdu }
     * 
     */
    public ArealObjectStatePdu createArealObjectStatePdu() {
        return new ArealObjectStatePdu();
    }

    /**
     * Create an instance of {@link ArticulationParameter }
     * 
     */
    public ArticulationParameter createArticulationParameter() {
        return new ArticulationParameter();
    }

    /**
     * Create an instance of {@link Vector3Double }
     * 
     */
    public Vector3Double createVector3Double() {
        return new Vector3Double();
    }

    /**
     * Create an instance of {@link AcousticEmitterSystem }
     * 
     */
    public AcousticEmitterSystem createAcousticEmitterSystem() {
        return new AcousticEmitterSystem();
    }

    /**
     * Create an instance of {@link StartResumePdu }
     * 
     */
    public StartResumePdu createStartResumePdu() {
        return new StartResumePdu();
    }

    /**
     * Create an instance of {@link ActionRequestReliablePdu }
     * 
     */
    public ActionRequestReliablePdu createActionRequestReliablePdu() {
        return new ActionRequestReliablePdu();
    }

    /**
     * Create an instance of {@link SetRecordReliablePdu }
     * 
     */
    public SetRecordReliablePdu createSetRecordReliablePdu() {
        return new SetRecordReliablePdu();
    }

    /**
     * Create an instance of {@link LayerHeader }
     * 
     */
    public LayerHeader createLayerHeader() {
        return new LayerHeader();
    }

    /**
     * Create an instance of {@link EventReportPdu }
     * 
     */
    public EventReportPdu createEventReportPdu() {
        return new EventReportPdu();
    }

    /**
     * Create an instance of {@link IffAtcNavAidsLayer1Pdu }
     * 
     */
    public IffAtcNavAidsLayer1Pdu createIffAtcNavAidsLayer1Pdu() {
        return new IffAtcNavAidsLayer1Pdu();
    }

    /**
     * Create an instance of {@link GridAxisRecordRepresentation2 }
     * 
     */
    public GridAxisRecordRepresentation2 createGridAxisRecordRepresentation2() {
        return new GridAxisRecordRepresentation2();
    }

    /**
     * Create an instance of {@link AcousticEmitter }
     * 
     */
    public AcousticEmitter createAcousticEmitter() {
        return new AcousticEmitter();
    }

    /**
     * Create an instance of {@link AcousticBeamFundamentalParameter }
     * 
     */
    public AcousticBeamFundamentalParameter createAcousticBeamFundamentalParameter() {
        return new AcousticBeamFundamentalParameter();
    }

    /**
     * Create an instance of {@link ResupplyOfferPdu }
     * 
     */
    public ResupplyOfferPdu createResupplyOfferPdu() {
        return new ResupplyOfferPdu();
    }

    /**
     * Create an instance of {@link AggregateMarking }
     * 
     */
    public AggregateMarking createAggregateMarking() {
        return new AggregateMarking();
    }

    /**
     * Create an instance of {@link TransferControlRequestPdu }
     * 
     */
    public TransferControlRequestPdu createTransferControlRequestPdu() {
        return new TransferControlRequestPdu();
    }

    /**
     * Create an instance of {@link DeadReckoningParameter }
     * 
     */
    public DeadReckoningParameter createDeadReckoningParameter() {
        return new DeadReckoningParameter();
    }

    /**
     * Create an instance of {@link TwoByteChunk }
     * 
     */
    public TwoByteChunk createTwoByteChunk() {
        return new TwoByteChunk();
    }

    /**
     * Create an instance of {@link SyntheticEnvironmentFamilyPdu }
     * 
     */
    public SyntheticEnvironmentFamilyPdu createSyntheticEnvironmentFamilyPdu() {
        return new SyntheticEnvironmentFamilyPdu();
    }

    /**
     * Create an instance of {@link DistributedEmissionsFamilyPdu }
     * 
     */
    public DistributedEmissionsFamilyPdu createDistributedEmissionsFamilyPdu() {
        return new DistributedEmissionsFamilyPdu();
    }

    /**
     * Create an instance of {@link ReceiverPdu }
     * 
     */
    public ReceiverPdu createReceiverPdu() {
        return new ReceiverPdu();
    }

    /**
     * Create an instance of {@link GridAxisRecord }
     * 
     */
    public GridAxisRecord createGridAxisRecord() {
        return new GridAxisRecord();
    }

    /**
     * Create an instance of {@link AngularVelocityVector }
     * 
     */
    public AngularVelocityVector createAngularVelocityVector() {
        return new AngularVelocityVector();
    }

    /**
     * Create an instance of {@link IntercomSignalPdu }
     * 
     */
    public IntercomSignalPdu createIntercomSignalPdu() {
        return new IntercomSignalPdu();
    }

    /**
     * Create an instance of {@link DataReliablePdu }
     * 
     */
    public DataReliablePdu createDataReliablePdu() {
        return new DataReliablePdu();
    }

    /**
     * Create an instance of {@link VariableDatum }
     * 
     */
    public VariableDatum createVariableDatum() {
        return new VariableDatum();
    }

    /**
     * Create an instance of {@link DataPdu }
     * 
     */
    public DataPdu createDataPdu() {
        return new DataPdu();
    }

    /**
     * Create an instance of {@link SupplyQuantity }
     * 
     */
    public SupplyQuantity createSupplyQuantity() {
        return new SupplyQuantity();
    }

    /**
     * Create an instance of {@link EmitterSystem }
     * 
     */
    public EmitterSystem createEmitterSystem() {
        return new EmitterSystem();
    }

    /**
     * Create an instance of {@link EntityStatePdu }
     * 
     */
    public EntityStatePdu createEntityStatePdu() {
        return new EntityStatePdu();
    }

    /**
     * Create an instance of {@link CommentPdu }
     * 
     */
    public CommentPdu createCommentPdu() {
        return new CommentPdu();
    }

    /**
     * Create an instance of {@link DesignatorPdu }
     * 
     */
    public DesignatorPdu createDesignatorPdu() {
        return new DesignatorPdu();
    }

    /**
     * Create an instance of {@link MinefieldFamilyPdu }
     * 
     */
    public MinefieldFamilyPdu createMinefieldFamilyPdu() {
        return new MinefieldFamilyPdu();
    }

    /**
     * Create an instance of {@link Pdu }
     * 
     */
    public Pdu createPdu() {
        return new Pdu();
    }

    /**
     * Create an instance of {@link RemoveEntityPdu }
     * 
     */
    public RemoveEntityPdu createRemoveEntityPdu() {
        return new RemoveEntityPdu();
    }

    /**
     * Create an instance of {@link TrackJamTarget }
     * 
     */
    public TrackJamTarget createTrackJamTarget() {
        return new TrackJamTarget();
    }

    /**
     * Create an instance of {@link FastEntityStatePdu }
     * 
     */
    public FastEntityStatePdu createFastEntityStatePdu() {
        return new FastEntityStatePdu();
    }

    /**
     * Create an instance of {@link WarfareFamilyPdu }
     * 
     */
    public WarfareFamilyPdu createWarfareFamilyPdu() {
        return new WarfareFamilyPdu();
    }

    /**
     * Create an instance of {@link SeesPdu }
     * 
     */
    public SeesPdu createSeesPdu() {
        return new SeesPdu();
    }

    /**
     * Create an instance of {@link NamedLocation }
     * 
     */
    public NamedLocation createNamedLocation() {
        return new NamedLocation();
    }

    /**
     * Create an instance of {@link LogisticsFamilyPdu }
     * 
     */
    public LogisticsFamilyPdu createLogisticsFamilyPdu() {
        return new LogisticsFamilyPdu();
    }

    /**
     * Create an instance of {@link IntercomControlPdu }
     * 
     */
    public IntercomControlPdu createIntercomControlPdu() {
        return new IntercomControlPdu();
    }

    /**
     * Create an instance of {@link ActionResponsePdu }
     * 
     */
    public ActionResponsePdu createActionResponsePdu() {
        return new ActionResponsePdu();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link SphericalHarmonicAntennaPattern }
     * 
     */
    public SphericalHarmonicAntennaPattern createSphericalHarmonicAntennaPattern() {
        return new SphericalHarmonicAntennaPattern();
    }

    /**
     * Create an instance of {@link CreateEntityReliablePdu }
     * 
     */
    public CreateEntityReliablePdu createCreateEntityReliablePdu() {
        return new CreateEntityReliablePdu();
    }

    /**
     * Create an instance of {@link EnvironmentalProcessPdu }
     * 
     */
    public EnvironmentalProcessPdu createEnvironmentalProcessPdu() {
        return new EnvironmentalProcessPdu();
    }

    /**
     * Create an instance of {@link SimulationAddress }
     * 
     */
    public SimulationAddress createSimulationAddress() {
        return new SimulationAddress();
    }

    /**
     * Create an instance of {@link CollisionElasticPdu }
     * 
     */
    public CollisionElasticPdu createCollisionElasticPdu() {
        return new CollisionElasticPdu();
    }

    /**
     * Create an instance of {@link MinefieldResponseNackPdu }
     * 
     */
    public MinefieldResponseNackPdu createMinefieldResponseNackPdu() {
        return new MinefieldResponseNackPdu();
    }

    /**
     * Create an instance of {@link FirePdu }
     * 
     */
    public FirePdu createFirePdu() {
        return new FirePdu();
    }

    /**
     * Create an instance of {@link RecordSet }
     * 
     */
    public RecordSet createRecordSet() {
        return new RecordSet();
    }

    /**
     * Create an instance of {@link BurstDescriptor }
     * 
     */
    public BurstDescriptor createBurstDescriptor() {
        return new BurstDescriptor();
    }

    /**
     * Create an instance of {@link GridAxisRecordRepresentation1 }
     * 
     */
    public GridAxisRecordRepresentation1 createGridAxisRecordRepresentation1() {
        return new GridAxisRecordRepresentation1();
    }

    /**
     * Create an instance of {@link ActionRequestPdu }
     * 
     */
    public ActionRequestPdu createActionRequestPdu() {
        return new ActionRequestPdu();
    }

    /**
     * Create an instance of {@link ObjectType }
     * 
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link FourByteChunk }
     * 
     */
    public FourByteChunk createFourByteChunk() {
        return new FourByteChunk();
    }

    /**
     * Create an instance of {@link RadioCommunicationsFamilyPdu }
     * 
     */
    public RadioCommunicationsFamilyPdu createRadioCommunicationsFamilyPdu() {
        return new RadioCommunicationsFamilyPdu();
    }

    /**
     * Create an instance of {@link CollisionPdu }
     * 
     */
    public CollisionPdu createCollisionPdu() {
        return new CollisionPdu();
    }

    /**
     * Create an instance of {@link ActionResponseReliablePdu }
     * 
     */
    public ActionResponseReliablePdu createActionResponseReliablePdu() {
        return new ActionResponseReliablePdu();
    }

    /**
     * Create an instance of {@link StopFreezePdu }
     * 
     */
    public StopFreezePdu createStopFreezePdu() {
        return new StopFreezePdu();
    }

    /**
     * Create an instance of {@link BeamAntennaPattern }
     * 
     */
    public BeamAntennaPattern createBeamAntennaPattern() {
        return new BeamAntennaPattern();
    }

    /**
     * Create an instance of {@link ElectronicEmissionBeamData }
     * 
     */
    public ElectronicEmissionBeamData createElectronicEmissionBeamData() {
        return new ElectronicEmissionBeamData();
    }

    /**
     * Create an instance of {@link DataQueryReliablePdu }
     * 
     */
    public DataQueryReliablePdu createDataQueryReliablePdu() {
        return new DataQueryReliablePdu();
    }

    /**
     * Create an instance of {@link Orientation }
     * 
     */
    public Orientation createOrientation() {
        return new Orientation();
    }

    /**
     * Create an instance of {@link SetDataReliablePdu }
     * 
     */
    public SetDataReliablePdu createSetDataReliablePdu() {
        return new SetDataReliablePdu();
    }

    /**
     * Create an instance of {@link FundamentalParameterDataIff }
     * 
     */
    public FundamentalParameterDataIff createFundamentalParameterDataIff() {
        return new FundamentalParameterDataIff();
    }

    /**
     * Create an instance of {@link EntityType }
     * 
     */
    public EntityType createEntityType() {
        return new EntityType();
    }

    /**
     * Create an instance of {@link EntityStateUpdatePdu }
     * 
     */
    public EntityStateUpdatePdu createEntityStateUpdatePdu() {
        return new EntityStateUpdatePdu();
    }

    /**
     * Create an instance of {@link RepairResponsePdu }
     * 
     */
    public RepairResponsePdu createRepairResponsePdu() {
        return new RepairResponsePdu();
    }

    /**
     * Create an instance of {@link StopFreezeReliablePdu }
     * 
     */
    public StopFreezeReliablePdu createStopFreezeReliablePdu() {
        return new StopFreezeReliablePdu();
    }

    /**
     * Create an instance of {@link SignalPdu }
     * 
     */
    public SignalPdu createSignalPdu() {
        return new SignalPdu();
    }

    /**
     * Create an instance of {@link SimulationManagementFamilyPdu }
     * 
     */
    public SimulationManagementFamilyPdu createSimulationManagementFamilyPdu() {
        return new SimulationManagementFamilyPdu();
    }

    /**
     * Create an instance of {@link Relationship }
     * 
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link IffFundamentalData }
     * 
     */
    public IffFundamentalData createIffFundamentalData() {
        return new IffFundamentalData();
    }

    /**
     * Create an instance of {@link SystemID }
     * 
     */
    public SystemID createSystemID() {
        return new SystemID();
    }

    /**
     * Create an instance of {@link MinefieldDataPdu }
     * 
     */
    public MinefieldDataPdu createMinefieldDataPdu() {
        return new MinefieldDataPdu();
    }

    /**
     * Create an instance of {@link AntennaLocation }
     * 
     */
    public AntennaLocation createAntennaLocation() {
        return new AntennaLocation();
    }

    /**
     * Create an instance of {@link AcousticEmitterSystemData }
     * 
     */
    public AcousticEmitterSystemData createAcousticEmitterSystemData() {
        return new AcousticEmitterSystemData();
    }

    /**
     * Create an instance of {@link ApaData }
     * 
     */
    public ApaData createApaData() {
        return new ApaData();
    }

    /**
     * Create an instance of {@link IsGroupOfPdu }
     * 
     */
    public IsGroupOfPdu createIsGroupOfPdu() {
        return new IsGroupOfPdu();
    }

    /**
     * Create an instance of {@link ShaftRPMs }
     * 
     */
    public ShaftRPMs createShaftRPMs() {
        return new ShaftRPMs();
    }

    /**
     * Create an instance of {@link AggregateType }
     * 
     */
    public AggregateType createAggregateType() {
        return new AggregateType();
    }

    /**
     * Create an instance of {@link VectoringNozzleSystemData }
     * 
     */
    public VectoringNozzleSystemData createVectoringNozzleSystemData() {
        return new VectoringNozzleSystemData();
    }

    /**
     * Create an instance of {@link EntityManagementFamilyPdu }
     * 
     */
    public EntityManagementFamilyPdu createEntityManagementFamilyPdu() {
        return new EntityManagementFamilyPdu();
    }

    /**
     * Create an instance of {@link EntityID }
     * 
     */
    public EntityID createEntityID() {
        return new EntityID();
    }

    /**
     * Create an instance of {@link Vector3Float }
     * 
     */
    public Vector3Float createVector3Float() {
        return new Vector3Float();
    }

    /**
     * Create an instance of {@link ModulationType }
     * 
     */
    public ModulationType createModulationType() {
        return new ModulationType();
    }

    /**
     * Create an instance of {@link LinearObjectStatePdu }
     * 
     */
    public LinearObjectStatePdu createLinearObjectStatePdu() {
        return new LinearObjectStatePdu();
    }

    /**
     * Create an instance of {@link Marking }
     * 
     */
    public Marking createMarking() {
        return new Marking();
    }

    /**
     * Create an instance of {@link IsPartOfPdu }
     * 
     */
    public IsPartOfPdu createIsPartOfPdu() {
        return new IsPartOfPdu();
    }

    /**
     * Create an instance of {@link ElectronicEmissionSystemData }
     * 
     */
    public ElectronicEmissionSystemData createElectronicEmissionSystemData() {
        return new ElectronicEmissionSystemData();
    }

    /**
     * Create an instance of {@link ClockTime }
     * 
     */
    public ClockTime createClockTime() {
        return new ClockTime();
    }

    /**
     * Create an instance of {@link CreateEntityPdu }
     * 
     */
    public CreateEntityPdu createCreateEntityPdu() {
        return new CreateEntityPdu();
    }

    /**
     * Create an instance of {@link GriddedDataPdu }
     * 
     */
    public GriddedDataPdu createGriddedDataPdu() {
        return new GriddedDataPdu();
    }

    /**
     * Create an instance of {@link EventID }
     * 
     */
    public EventID createEventID() {
        return new EventID();
    }

    /**
     * Create an instance of {@link ElectronicEmissionsPdu }
     * 
     */
    public ElectronicEmissionsPdu createElectronicEmissionsPdu() {
        return new ElectronicEmissionsPdu();
    }

}
