//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pointObjectStatePdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pointObjectStatePdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}syntheticEnvironmentFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="forceID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="modifications" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="objectAppearance" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="objectID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="objectLocation" type="{}vector3Double" minOccurs="0"/>
 *         &lt;element name="objectOrientation" type="{}orientation" minOccurs="0"/>
 *         &lt;element name="objectType" type="{}objectType" minOccurs="0"/>
 *         &lt;element name="pad2" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="receivingID" type="{}simulationAddress" minOccurs="0"/>
 *         &lt;element name="referencedObjectID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="requesterID" type="{}simulationAddress" minOccurs="0"/>
 *         &lt;element name="updateNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pointObjectStatePdu", propOrder = {
    "forceID",
    "modifications",
    "objectAppearance",
    "objectID",
    "objectLocation",
    "objectOrientation",
    "objectType",
    "pad2",
    "receivingID",
    "referencedObjectID",
    "requesterID",
    "updateNumber"
})
public class PointObjectStatePdu
    extends SyntheticEnvironmentFamilyPdu
{

    protected short forceID;
    protected short modifications;
    protected double objectAppearance;
    protected EntityID objectID;
    protected Vector3Double objectLocation;
    protected Orientation objectOrientation;
    protected ObjectType objectType;
    protected long pad2;
    protected SimulationAddress receivingID;
    protected EntityID referencedObjectID;
    protected SimulationAddress requesterID;
    protected int updateNumber;

    /**
     * Gets the value of the forceID property.
     * 
     */
    public short getForceID() {
        return forceID;
    }

    /**
     * Sets the value of the forceID property.
     * 
     */
    public void setForceID(short value) {
        this.forceID = value;
    }

    /**
     * Gets the value of the modifications property.
     * 
     */
    public short getModifications() {
        return modifications;
    }

    /**
     * Sets the value of the modifications property.
     * 
     */
    public void setModifications(short value) {
        this.modifications = value;
    }

    /**
     * Gets the value of the objectAppearance property.
     * 
     */
    public double getObjectAppearance() {
        return objectAppearance;
    }

    /**
     * Sets the value of the objectAppearance property.
     * 
     */
    public void setObjectAppearance(double value) {
        this.objectAppearance = value;
    }

    /**
     * Gets the value of the objectID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getObjectID() {
        return objectID;
    }

    /**
     * Sets the value of the objectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setObjectID(EntityID value) {
        this.objectID = value;
    }

    /**
     * Gets the value of the objectLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Vector3Double }
     *     
     */
    public Vector3Double getObjectLocation() {
        return objectLocation;
    }

    /**
     * Sets the value of the objectLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector3Double }
     *     
     */
    public void setObjectLocation(Vector3Double value) {
        this.objectLocation = value;
    }

    /**
     * Gets the value of the objectOrientation property.
     * 
     * @return
     *     possible object is
     *     {@link Orientation }
     *     
     */
    public Orientation getObjectOrientation() {
        return objectOrientation;
    }

    /**
     * Sets the value of the objectOrientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Orientation }
     *     
     */
    public void setObjectOrientation(Orientation value) {
        this.objectOrientation = value;
    }

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectType }
     *     
     */
    public ObjectType getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectType }
     *     
     */
    public void setObjectType(ObjectType value) {
        this.objectType = value;
    }

    /**
     * Gets the value of the pad2 property.
     * 
     */
    public long getPad2() {
        return pad2;
    }

    /**
     * Sets the value of the pad2 property.
     * 
     */
    public void setPad2(long value) {
        this.pad2 = value;
    }

    /**
     * Gets the value of the receivingID property.
     * 
     * @return
     *     possible object is
     *     {@link SimulationAddress }
     *     
     */
    public SimulationAddress getReceivingID() {
        return receivingID;
    }

    /**
     * Sets the value of the receivingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimulationAddress }
     *     
     */
    public void setReceivingID(SimulationAddress value) {
        this.receivingID = value;
    }

    /**
     * Gets the value of the referencedObjectID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getReferencedObjectID() {
        return referencedObjectID;
    }

    /**
     * Sets the value of the referencedObjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setReferencedObjectID(EntityID value) {
        this.referencedObjectID = value;
    }

    /**
     * Gets the value of the requesterID property.
     * 
     * @return
     *     possible object is
     *     {@link SimulationAddress }
     *     
     */
    public SimulationAddress getRequesterID() {
        return requesterID;
    }

    /**
     * Sets the value of the requesterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimulationAddress }
     *     
     */
    public void setRequesterID(SimulationAddress value) {
        this.requesterID = value;
    }

    /**
     * Gets the value of the updateNumber property.
     * 
     */
    public int getUpdateNumber() {
        return updateNumber;
    }

    /**
     * Sets the value of the updateNumber property.
     * 
     */
    public void setUpdateNumber(int value) {
        this.updateNumber = value;
    }

}
