//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resupplyCancelPdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resupplyCancelPdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}logisticsFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="receivingEntityID" type="{}entityID" minOccurs="0"/>
 *         &lt;element name="supplyingEntityID" type="{}entityID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resupplyCancelPdu", propOrder = {
    "receivingEntityID",
    "supplyingEntityID"
})
public class ResupplyCancelPdu
    extends LogisticsFamilyPdu
{

    protected EntityID receivingEntityID;
    protected EntityID supplyingEntityID;

    /**
     * Gets the value of the receivingEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getReceivingEntityID() {
        return receivingEntityID;
    }

    /**
     * Sets the value of the receivingEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setReceivingEntityID(EntityID value) {
        this.receivingEntityID = value;
    }

    /**
     * Gets the value of the supplyingEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link EntityID }
     *     
     */
    public EntityID getSupplyingEntityID() {
        return supplyingEntityID;
    }

    /**
     * Sets the value of the supplyingEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityID }
     *     
     */
    public void setSupplyingEntityID(EntityID value) {
        this.supplyingEntityID = value;
    }

}
