//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for signalPdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="signalPdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}radioCommunicationsFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="dataLength" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="encodingScheme" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="sampleRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="samples" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="tdlType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "signalPdu", propOrder = {
    "dataLength",
    "encodingScheme",
    "sampleRate",
    "samples",
    "tdlType"
})
public class SignalPdu
    extends RadioCommunicationsFamilyPdu
{

    protected short dataLength;
    protected int encodingScheme;
    protected int sampleRate;
    protected short samples;
    protected int tdlType;

    /**
     * Gets the value of the dataLength property.
     * 
     */
    public short getDataLength() {
        return dataLength;
    }

    /**
     * Sets the value of the dataLength property.
     * 
     */
    public void setDataLength(short value) {
        this.dataLength = value;
    }

    /**
     * Gets the value of the encodingScheme property.
     * 
     */
    public int getEncodingScheme() {
        return encodingScheme;
    }

    /**
     * Sets the value of the encodingScheme property.
     * 
     */
    public void setEncodingScheme(int value) {
        this.encodingScheme = value;
    }

    /**
     * Gets the value of the sampleRate property.
     * 
     */
    public int getSampleRate() {
        return sampleRate;
    }

    /**
     * Sets the value of the sampleRate property.
     * 
     */
    public void setSampleRate(int value) {
        this.sampleRate = value;
    }

    /**
     * Gets the value of the samples property.
     * 
     */
    public short getSamples() {
        return samples;
    }

    /**
     * Sets the value of the samples property.
     * 
     */
    public void setSamples(short value) {
        this.samples = value;
    }

    /**
     * Gets the value of the tdlType property.
     * 
     */
    public int getTdlType() {
        return tdlType;
    }

    /**
     * Sets the value of the tdlType property.
     * 
     */
    public void setTdlType(int value) {
        this.tdlType = value;
    }

}
