//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 02:05:02 PM PST 
//


package edu.nps.moves.jaxb.dis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stopFreezePdu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stopFreezePdu">
 *   &lt;complexContent>
 *     &lt;extension base="{}simulationManagementFamilyPdu">
 *       &lt;sequence>
 *         &lt;element name="frozenBehavior" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="padding1" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="realWorldTime" type="{}clockTime" minOccurs="0"/>
 *         &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="requestID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stopFreezePdu", propOrder = {
    "frozenBehavior",
    "padding1",
    "realWorldTime",
    "reason",
    "requestID"
})
public class StopFreezePdu
    extends SimulationManagementFamilyPdu
{

    protected short frozenBehavior;
    protected short padding1;
    protected ClockTime realWorldTime;
    protected short reason;
    protected long requestID;

    /**
     * Gets the value of the frozenBehavior property.
     * 
     */
    public short getFrozenBehavior() {
        return frozenBehavior;
    }

    /**
     * Sets the value of the frozenBehavior property.
     * 
     */
    public void setFrozenBehavior(short value) {
        this.frozenBehavior = value;
    }

    /**
     * Gets the value of the padding1 property.
     * 
     */
    public short getPadding1() {
        return padding1;
    }

    /**
     * Sets the value of the padding1 property.
     * 
     */
    public void setPadding1(short value) {
        this.padding1 = value;
    }

    /**
     * Gets the value of the realWorldTime property.
     * 
     * @return
     *     possible object is
     *     {@link ClockTime }
     *     
     */
    public ClockTime getRealWorldTime() {
        return realWorldTime;
    }

    /**
     * Sets the value of the realWorldTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClockTime }
     *     
     */
    public void setRealWorldTime(ClockTime value) {
        this.realWorldTime = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     */
    public short getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     */
    public void setReason(short value) {
        this.reason = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     */
    public long getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     */
    public void setRequestID(long value) {
        this.requestID = value;
    }

}
