/*
 * ListenerEditFrame.java
 * 
 * The sole purpose of this class is to edit the UDP Listener profile. This is
 * presented to the user when they click on the "new listener" button presented
 * in UDPCaptureFrame.<p>
 * 
 * Created on June 1, 2009, 6:38 PM
 */

package edu.nps.moves.xplane;


import java.net.InetAddress;

/**
 *
 * @author  tmrashid
 * @version 1.0
 */
public class ListenerEditFrame extends javax.swing.JFrame {

    public final boolean DEBUG = true;
    private final String GUI_TITLE = "X-Plane UDP to DIS Listener Editor";
    
    public final String DEFAULT_ENTITY_NAME = "X-Plane";
    public final String DEFAULT_LISTEN_ADDRESS = "239.3.2.2";
    
    
    public final int DEFAULT_DATA_PORT = 49000;
    public final int DEFAULT_SNAP_PORT = 49001;
    
    public final String DEFAULT_OUTPUT_GROUP = "239.1.2.3";
    public final int DEFAULT_OUTPUT_MULTICAST_PORT = 62040;
    
    private int idCounter = 0;
 
    XPlaneUDPListener myListener;
    
    
    
 
    /** Creates new form ListenerEditFrame */
    public ListenerEditFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        captureParameterPanel = new javax.swing.JPanel();
        applyButton = new javax.swing.JButton();
        portField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        snapPortField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messagePanel = new javax.swing.JTextArea();
        clearMessagePanelButton = new javax.swing.JButton();
        typeComboBox = new javax.swing.JComboBox();
        outputParametPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        outputMulticastAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        outputMulticastPortField = new javax.swing.JTextField();
        kmlRadioButton = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        chatServerTextField = new javax.swing.JTextField();
        loginNameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        xmppConnectionResource = new javax.swing.JTextField();
        xmppRadioButton = new javax.swing.JRadioButton();
        multicastRadioButton = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kmlDestination = new javax.swing.JTextField();
        kmlUpdateRateTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        chatRoomTextField = new javax.swing.JTextField();
        fixedPositionRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(GUI_TITLE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);

        captureParameterPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        applyButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        applyButton.setText("APPLY ALL AND CLOSE");
        applyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applyButtonMouseClicked(evt);
            }
        });

        portField.setFont(new java.awt.Font("Tahoma", 1, 14));
        portField.setText(""+DEFAULT_DATA_PORT);
        portField.setPreferredSize(new java.awt.Dimension(46, 20));
        portField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                portFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                portFieldFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Data Port");

        addressField.setFont(new java.awt.Font("Tahoma", 1, 14));
        addressField.setText(DEFAULT_LISTEN_ADDRESS);
        addressField.setPreferredSize(new java.awt.Dimension(66, 20));
        addressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFieldFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Listening Address");

        idField.setFont(new java.awt.Font("Tahoma", 1, 14));
        idField.setText(""+idCounter);
        idField.setPreferredSize(new java.awt.Dimension(89, 20));
        idField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idFieldFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel11.setText("Entity ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Entity Type");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel14.setText("Listener Parameters");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel20.setText("Snap Port");

        snapPortField.setFont(new java.awt.Font("Tahoma", 1, 14));
        snapPortField.setText(""+DEFAULT_SNAP_PORT);
        snapPortField.setMinimumSize(new java.awt.Dimension(6, 20));
        snapPortField.setPreferredSize(new java.awt.Dimension(69, 20));
        snapPortField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snapPortFieldActionPerformed(evt);
            }
        });
        snapPortField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                snapPortFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                snapPortFieldFocusLost(evt);
            }
        });

        jLabel9.setText("Listening ConnectionType");

        messagePanel.setColumns(20);
        messagePanel.setEditable(false);
        messagePanel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        messagePanel.setRows(5);
        jScrollPane1.setViewportView(messagePanel);

        clearMessagePanelButton.setText("CLEAR");
        clearMessagePanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMessagePanelButtonMouseClicked(evt);
            }
        });

        typeComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Generic" }));
        typeComboBox.setToolTipText("The choices availabe here are set in the file specificAir.txt which is in the common directory");

        javax.swing.GroupLayout captureParameterPanelLayout = new javax.swing.GroupLayout(captureParameterPanel);
        captureParameterPanel.setLayout(captureParameterPanelLayout);
        captureParameterPanelLayout.setHorizontalGroup(
            captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, captureParameterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, captureParameterPanelLayout.createSequentialGroup()
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(captureParameterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, captureParameterPanelLayout.createSequentialGroup()
                        .addGroup(captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(typeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 117, Short.MAX_VALUE)
                            .addComponent(addressField, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(captureParameterPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(portField, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, captureParameterPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(snapPortField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(captureParameterPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(captureParameterPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(captureParameterPanelLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(clearMessagePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addGroup(captureParameterPanelLayout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel14)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        captureParameterPanelLayout.setVerticalGroup(
            captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(captureParameterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(captureParameterPanelLayout.createSequentialGroup()
                        .addGroup(captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(captureParameterPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(captureParameterPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(captureParameterPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(snapPortField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(captureParameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(clearMessagePanelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        outputParametPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel6.setText("Output Parameters");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Address");

        outputMulticastAddress.setFont(new java.awt.Font("Tahoma", 1, 14));
        outputMulticastAddress.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        outputMulticastAddress.setText(DEFAULT_OUTPUT_GROUP);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setText("Port");

        outputMulticastPortField.setFont(new java.awt.Font("Tahoma", 1, 14));
        outputMulticastPortField.setText(""+DEFAULT_OUTPUT_MULTICAST_PORT);
        outputMulticastPortField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                outputMulticastPortFieldFocusLost(evt);
            }
        });

        kmlRadioButton.setFont(new java.awt.Font("Tahoma", 1, 16));
        kmlRadioButton.setText("Write KML to URL");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setText("Login Name");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel13.setText("Chat Server");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel15.setText("Resource");

        chatServerTextField.setFont(new java.awt.Font("Tahoma", 1, 14));

        loginNameTextField.setFont(new java.awt.Font("Tahoma", 1, 14));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setText("  Chat Room ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel12.setText("Password");

        xmppConnectionResource.setFont(new java.awt.Font("Tahoma", 1, 14));
        xmppConnectionResource.setText("xplane");

        xmppRadioButton.setFont(new java.awt.Font("Tahoma", 1, 16));
        xmppRadioButton.setText("DIS Byte via XMPP");

        multicastRadioButton.setFont(new java.awt.Font("Tahoma", 1, 16));
        multicastRadioButton.setText("Multicast DIS");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel16.setText("Update Every");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("URL/Location");

        kmlDestination.setEditable(false);
        kmlDestination.setFont(new java.awt.Font("Tahoma", 1, 14));
        kmlDestination.setText(".");
        kmlDestination.setEnabled(false);

        kmlUpdateRateTextField.setFont(new java.awt.Font("Tahoma", 1, 14));
        kmlUpdateRateTextField.setText("60");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel18.setText("Seconds");

        passwordField.setFont(new java.awt.Font("Tahoma", 1, 14));
        passwordField.setMinimumSize(new java.awt.Dimension(20, 22));
        passwordField.setPreferredSize(new java.awt.Dimension(147, 22));

        chatRoomTextField.setFont(new java.awt.Font("Tahoma", 1, 14));

        fixedPositionRadioButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        fixedPositionRadioButton.setText("Fix Entity Location to 0,0,0 for X3D");
        fixedPositionRadioButton.setToolTipText("Selecting this sets the values 0,0,0 in the position element of the ESPDU \nAttitude information will still be available");

        javax.swing.GroupLayout outputParametPanelLayout = new javax.swing.GroupLayout(outputParametPanel);
        outputParametPanel.setLayout(outputParametPanelLayout);
        outputParametPanelLayout.setHorizontalGroup(
            outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputParametPanelLayout.createSequentialGroup()
                .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(outputParametPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel13))
                    .addGroup(outputParametPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel10))
                        .addGap(12, 12, 12)
                        .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xmppConnectionResource, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(outputParametPanelLayout.createSequentialGroup()
                                .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(loginNameTextField)
                                    .addComponent(chatServerTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                                .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(outputParametPanelLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chatRoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(outputParametPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(outputParametPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(outputParametPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kmlUpdateRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(outputParametPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kmlDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(outputParametPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(outputMulticastAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputMulticastPortField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(fixedPositionRadioButton))
                    .addGroup(outputParametPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(xmppRadioButton)
                                .addComponent(kmlRadioButton))
                            .addGroup(outputParametPanelLayout.createSequentialGroup()
                                .addComponent(multicastRadioButton)
                                .addGap(42, 42, 42))))
                    .addGroup(outputParametPanelLayout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel6)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        outputParametPanelLayout.setVerticalGroup(
            outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputParametPanelLayout.createSequentialGroup()
                .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(outputParametPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(multicastRadioButton))
                    .addGroup(outputParametPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(outputMulticastPortField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(outputMulticastAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fixedPositionRadioButton))
                .addGap(19, 19, 19)
                .addComponent(xmppRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(chatRoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chatServerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(xmppConnectionResource, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(loginNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(kmlRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kmlDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(outputParametPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(kmlUpdateRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(captureParameterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputParametPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(captureParameterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(outputParametPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void portFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_portFieldFocusLost
// Makes sure that an integer is put into the port text Field
    try{
        Integer.parseInt(portField.getText());
         //messagePanel.setText("");
    }catch (java.lang.NumberFormatException nfe){
        //portField.setText("");    
        messagePanel.append("Port Number Must be an Integer\n");
        portField.setBackground(java.awt.Color.ORANGE); 
    }
}//GEN-LAST:event_portFieldFocusLost
private void applyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyButtonMouseClicked
// Cloase the editor window
     if( applyChanges(myListener))
     {
      this.setVisible(false);
            this.dispose();
     }
}//GEN-LAST:event_applyButtonMouseClicked

private void outputMulticastPortFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_outputMulticastPortFieldFocusLost
// TODO add your handling code here:
     try{
        Integer.parseInt(outputMulticastPortField.getText());
          //messagePanel.setText("");
    }catch (java.lang.NumberFormatException nfe){
        //portField.setText("");    
        messagePanel.append("Port Number Must be an Integer\n");
        outputMulticastPortField.setBackground(java.awt.Color.ORANGE); 
        
      
    }
    
}//GEN-LAST:event_outputMulticastPortFieldFocusLost

private void idFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFieldFocusLost
// TODO add your handling code here:
    try{
        Integer.parseInt(idField.getText());
          //messagePanel.setText("");
    }catch (NumberFormatException nfe){
           //idField.setText("");
           idField.setBackground(java.awt.Color.ORANGE);
          messagePanel.append("Entity ID must be an integer!\n");  
          
        }
    
}//GEN-LAST:event_idFieldFocusLost

private void snapPortFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snapPortFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_snapPortFieldActionPerformed

private void idFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFieldFocusGained
// TODO add your handling code here:
    idField.setBackground(java.awt.Color.WHITE);
    //messagePanel.setText("");
}//GEN-LAST:event_idFieldFocusGained

private void snapPortFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_snapPortFieldFocusGained
// TODO add your handling code here:
      snapPortField.setBackground(java.awt.Color.WHITE);
    //messagePanel.setText("");
}//GEN-LAST:event_snapPortFieldFocusGained

private void portFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_portFieldFocusGained
// TODO add your handling code here:
      portField.setBackground(java.awt.Color.WHITE);
    //messagePanel.setText("");
}//GEN-LAST:event_portFieldFocusGained

private void snapPortFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_snapPortFieldFocusLost
// TODO add your handling code here:
     try{
        Integer.parseInt(snapPortField.getText());
        //messagePanel.setText("");
    }catch (NumberFormatException nfe){
           //snapPortField.setText("");
           snapPortField.setBackground(java.awt.Color.ORANGE);
          messagePanel.append("Snap port must be an integer!\n");  
          
          
    }
}//GEN-LAST:event_snapPortFieldFocusLost

private void addressFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusLost
// TODO add your handling code here:
  try{
        InetAddress.getByName(addressField.getText());
   }catch(java.net.UnknownHostException ukh ){
       addressField.setBackground(java.awt.Color.ORANGE);
       messagePanel.append(addressField.getText() + " Does not appear to be a valid address\n");
   }
      
    
}//GEN-LAST:event_addressFieldFocusLost

private void addressFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusGained
// TODO add your handling code here:
     addressField.setBackground(java.awt.Color.WHITE);
}//GEN-LAST:event_addressFieldFocusGained

private void clearMessagePanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMessagePanelButtonMouseClicked
// TODO add your handling code here:
    messagePanel.setText("");
    
}//GEN-LAST:event_clearMessagePanelButtonMouseClicked



/**applies the changes to the the passed in selected listener
 * 
*
*/
    
public boolean applyChanges(XPlaneUDPListener selectedListener){
    
       String exceptionField = "undetermined";
    try{
         exceptionField = "Entity ID";
         selectedListener.setEntityID(Integer.parseInt(idField.getText()));
         
         //selectedListener.setEntityName(entityNameField.getText());
         exceptionField = "Listening Address";
         selectedListener.getConnectionManager().setAddress(addressField.getText());
         
          selectedListener.getConnectionManager().setListeningConnectionType(selectedListener.getConnectionManager().resolveConnectionType(addressField.getText()));
         
         //Call method to determine what type of connection this is
         
         
          exceptionField = "Data Port";
         selectedListener.getConnectionManager().setPort(Integer.parseInt(portField.getText()));
         exceptionField = "Snap Port";
         selectedListener.getConnectionManager().setSnapPort(Integer.parseInt(portField.getText()));
         selectedListener.getConnectionManager().setListeningConnectionType(selectedListener.getConnectionManager().getConnectionType());
         
         selectedListener.getConnectionManager().setMulticast(multicastRadioButton.isSelected());
       
         selectedListener.getConnectionManager().getMulticastSender().setMulticastGroup(outputMulticastAddress.getText());
          exceptionField = "Output Multicast Port";
         selectedListener.getConnectionManager().getMulticastSender().setPort(Integer.parseInt(outputMulticastPortField.getText()));
         
         selectedListener.setEntityPositionOutputFixed(fixedPositionRadioButton.isSelected());
         
     
         if (kmlRadioButton.isSelected()){
            selectedListener.getConnectionManager().setKml(kmlRadioButton.isSelected());
         }

          if (xmppRadioButton.isSelected()){
            selectedListener.getConnectionManager().setXmpp(xmppRadioButton.isSelected());
         }
         
        //}
         
    }catch(Exception e){
         messagePanel.setText(exceptionField + " Field is Missing Data");
      
        return false;
    }
     
  return true;
}


    public void initializeEditFrame(XPlaneUDPListener ul) {
        myListener = ul;
        try {
            
            
            if (DEBUG) System.out.println("Attempting to read file for ComboBox");
            typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(myListener.getXPlaneActor().getEntityTypes()));
            
            idField.setText("" + myListener.getID().getEntity());
            //entityNameField.setText(myListener.getEntityName());
            addressField.setText(myListener.getConnectionManager().getAddress());
            portField.setText("" + myListener.getConnectionManager().getPort());
            snapPortField.setText("" + myListener.getConnectionManager().getSnapPort());
        } catch (NullPointerException npe) {
            messagePanel.setText("The Listener Is Missing Required Data");
            messagePanel.setBackground(java.awt.Color.RED);
        }
        
        
        //Try to populate the Output Parameters
        
        

    }






    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new ListenerEditFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel captureParameterPanel;
    private javax.swing.JTextField chatRoomTextField;
    private javax.swing.JTextField chatServerTextField;
    private javax.swing.JButton clearMessagePanelButton;
    private javax.swing.JRadioButton fixedPositionRadioButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kmlDestination;
    private javax.swing.JRadioButton kmlRadioButton;
    private javax.swing.JTextField kmlUpdateRateTextField;
    private javax.swing.JTextField loginNameTextField;
    private javax.swing.JTextArea messagePanel;
    private javax.swing.JRadioButton multicastRadioButton;
    private javax.swing.JTextField outputMulticastAddress;
    private javax.swing.JTextField outputMulticastPortField;
    private javax.swing.JPanel outputParametPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField portField;
    private javax.swing.JTextField snapPortField;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JTextField xmppConnectionResource;
    private javax.swing.JRadioButton xmppRadioButton;
    // End of variables declaration//GEN-END:variables

}
