# C Console Executable Makefile autogenerated by premake
# Don't edit this file! Instead edit `premake.lua` then rerun `make`

ifndef CONFIG
  CONFIG=Debug
endif

ifeq ($(CONFIG),Debug)
  BINDIR := ../../bin
  LIBDIR := ../../lib
  OBJDIR := obj_gnu_DIS_debug
  OUTDIR := ../../bin
  CPPFLAGS := -MMD -D "_DEBUG" -I "../../cpp" -I "../../CppUtils"
  CFLAGS += $(CPPFLAGS) $(TARGET_ARCH) -fPIC -g
  CXXFLAGS := $(CFLAGS)
  LDFLAGS += -L$(BINDIR) -L$(LIBDIR) -shared
  LDDEPS :=
  RESFLAGS := -D "_DEBUG" -I "../../cpp" -I "../../CppUtils"
  TARGET := libDIS_debug.so
  BLDCMD = $(CC) -o $(OUTDIR)/$(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(TARGET_ARCH)
endif

ifeq ($(CONFIG),Release)
  BINDIR := ../../bin
  LIBDIR := ../../lib
  OBJDIR := obj_gnu_DIS
  OUTDIR := ../../bin
  CPPFLAGS := -MMD -I "../../cpp" -I "../../CppUtils"
  CFLAGS += $(CPPFLAGS) $(TARGET_ARCH) -fPIC -O2
  CXXFLAGS := $(CFLAGS)
  LDFLAGS += -L$(BINDIR) -L$(LIBDIR) -shared -s
  LDDEPS :=
  RESFLAGS := -I "../../cpp" -I "../../CppUtils"
  TARGET := libDIS.so
  BLDCMD = $(CC) -o $(OUTDIR)/$(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(TARGET_ARCH)
endif

OBJECTS := \
	$(OBJDIR)/ServiceRequestPdu.o \
	$(OBJDIR)/CommentPdu.o \
	$(OBJDIR)/RepairResponsePdu.o \
	$(OBJDIR)/BurstDescriptor.o \
	$(OBJDIR)/Vector3Double.o \
	$(OBJDIR)/DetonationPdu.o \
	$(OBJDIR)/AcknowledgePdu.o \
	$(OBJDIR)/CollisionPdu.o \
	$(OBJDIR)/RemoveEntityPdu.o \
	$(OBJDIR)/EntityStatePdu.o \
	$(OBJDIR)/ActionResponsePdu.o \
	$(OBJDIR)/VariableDatum.o \
	$(OBJDIR)/FirePdu.o \
	$(OBJDIR)/SetDataPdu.o \
	$(OBJDIR)/ActionRequestPdu.o \
	$(OBJDIR)/DeadReckoningParameter.o \
	$(OBJDIR)/EightByteChunk.o \
	$(OBJDIR)/RepairCompletePdu.o \
	$(OBJDIR)/CreateEntityPdu.o \
	$(OBJDIR)/Warfare.o \
	$(OBJDIR)/EventReportPdu.o \
	$(OBJDIR)/StartResumePdu.o \
	$(OBJDIR)/SimulationManagementPdu.o \
	$(OBJDIR)/DataQueryPdu.o \
	$(OBJDIR)/EntityID.o \
	$(OBJDIR)/EntityType.o \
	$(OBJDIR)/ResupplyReceivedPdu.o \
	$(OBJDIR)/Orientation.o \
	$(OBJDIR)/EventID.o \
	$(OBJDIR)/Pdu.o \
	$(OBJDIR)/LogisticsPdu.o \
	$(OBJDIR)/Vector3Float.o \
	$(OBJDIR)/StopFreezePdu.o \
	$(OBJDIR)/ResupplyOfferPdu.o \
	$(OBJDIR)/ClockTime.o \
	$(OBJDIR)/ResupplyCancelPdu.o \
	$(OBJDIR)/FixedDatum.o \
	$(OBJDIR)/ArticulationParameter.o \
	$(OBJDIR)/SupplyQuantity.o \
	$(OBJDIR)/DataStream.o \
	$(OBJDIR)/IncomingMessage.o \
	$(OBJDIR)/PacketFactory.o \
	$(OBJDIR)/Conversion.o \
	$(OBJDIR)/PDUBank.o \
	$(OBJDIR)/StreamUtils.o \

MKDIR_TYPE := msdos
CMD := $(subst \,\\,$(ComSpec)$(COMSPEC))
ifeq (,$(CMD))
  MKDIR_TYPE := posix
endif
ifeq (/bin/sh.exe,$(SHELL))
  MKDIR_TYPE := posix
endif
ifeq ($(MKDIR_TYPE),posix)
  CMD_MKBINDIR := mkdir -p $(BINDIR)
  CMD_MKLIBDIR := mkdir -p $(LIBDIR)
  CMD_MKOUTDIR := mkdir -p $(OUTDIR)
  CMD_MKOBJDIR := mkdir -p $(OBJDIR)
else
  CMD_MKBINDIR := $(CMD) /c if not exist $(subst /,\\,$(BINDIR)) mkdir $(subst /,\\,$(BINDIR))
  CMD_MKLIBDIR := $(CMD) /c if not exist $(subst /,\\,$(LIBDIR)) mkdir $(subst /,\\,$(LIBDIR))
  CMD_MKOUTDIR := $(CMD) /c if not exist $(subst /,\\,$(OUTDIR)) mkdir $(subst /,\\,$(OUTDIR))
  CMD_MKOBJDIR := $(CMD) /c if not exist $(subst /,\\,$(OBJDIR)) mkdir $(subst /,\\,$(OBJDIR))
endif

.PHONY: clean

$(OUTDIR)/$(TARGET): $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking DIS
	-@$(CMD_MKBINDIR)
	-@$(CMD_MKLIBDIR)
	-@$(CMD_MKOUTDIR)
	@$(BLDCMD)

clean:
	@echo Cleaning DIS
ifeq ($(MKDIR_TYPE),posix)
	-@rm -rf $(OUTDIR)/$(TARGET) $(OBJDIR)
else
	-@if exist $(subst /,\,$(OUTDIR)/$(TARGET)) del /q $(subst /,\,$(OUTDIR)/$(TARGET))
	-@if exist $(subst /,\,$(OBJDIR)) del /q $(subst /,\,$(OBJDIR))
	-@if exist $(subst /,\,$(OBJDIR)) rmdir /s /q $(subst /,\,$(OBJDIR))
endif

$(OBJDIR)/ServiceRequestPdu.o: ../../cpp/DIS/ServiceRequestPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/CommentPdu.o: ../../cpp/DIS/CommentPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/RepairResponsePdu.o: ../../cpp/DIS/RepairResponsePdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/BurstDescriptor.o: ../../cpp/DIS/BurstDescriptor.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/Vector3Double.o: ../../cpp/DIS/Vector3Double.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/DetonationPdu.o: ../../cpp/DIS/DetonationPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/AcknowledgePdu.o: ../../cpp/DIS/AcknowledgePdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/CollisionPdu.o: ../../cpp/DIS/CollisionPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/RemoveEntityPdu.o: ../../cpp/DIS/RemoveEntityPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/EntityStatePdu.o: ../../cpp/DIS/EntityStatePdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/ActionResponsePdu.o: ../../cpp/DIS/ActionResponsePdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/VariableDatum.o: ../../cpp/DIS/VariableDatum.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/FirePdu.o: ../../cpp/DIS/FirePdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/SetDataPdu.o: ../../cpp/DIS/SetDataPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/ActionRequestPdu.o: ../../cpp/DIS/ActionRequestPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/DeadReckoningParameter.o: ../../cpp/DIS/DeadReckoningParameter.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/EightByteChunk.o: ../../cpp/DIS/EightByteChunk.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/RepairCompletePdu.o: ../../cpp/DIS/RepairCompletePdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/CreateEntityPdu.o: ../../cpp/DIS/CreateEntityPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/Warfare.o: ../../cpp/DIS/Warfare.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/EventReportPdu.o: ../../cpp/DIS/EventReportPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/StartResumePdu.o: ../../cpp/DIS/StartResumePdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/SimulationManagementPdu.o: ../../cpp/DIS/SimulationManagementPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/DataQueryPdu.o: ../../cpp/DIS/DataQueryPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/EntityID.o: ../../cpp/DIS/EntityID.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/EntityType.o: ../../cpp/DIS/EntityType.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/ResupplyReceivedPdu.o: ../../cpp/DIS/ResupplyReceivedPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/Orientation.o: ../../cpp/DIS/Orientation.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/EventID.o: ../../cpp/DIS/EventID.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/Pdu.o: ../../cpp/DIS/Pdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/LogisticsPdu.o: ../../cpp/DIS/LogisticsPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/Vector3Float.o: ../../cpp/DIS/Vector3Float.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/StopFreezePdu.o: ../../cpp/DIS/StopFreezePdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/ResupplyOfferPdu.o: ../../cpp/DIS/ResupplyOfferPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/ClockTime.o: ../../cpp/DIS/ClockTime.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/ResupplyCancelPdu.o: ../../cpp/DIS/ResupplyCancelPdu.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/FixedDatum.o: ../../cpp/DIS/FixedDatum.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/ArticulationParameter.o: ../../cpp/DIS/ArticulationParameter.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/SupplyQuantity.o: ../../cpp/DIS/SupplyQuantity.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/DataStream.o: ../../CppUtils/DIS/DataStream.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/IncomingMessage.o: ../../CppUtils/DIS/IncomingMessage.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/PacketFactory.o: ../../CppUtils/DIS/PacketFactory.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/Conversion.o: ../../CppUtils/DIS/Conversion.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/PDUBank.o: ../../CppUtils/DIS/PDUBank.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/StreamUtils.o: ../../CppUtils/DIS/StreamUtils.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

-include $(OBJECTS:%.o=%.d)

